### ISSUE TITLE
How to check that I am correctly using CUDA to accelerate the dense solver

### ISSUE THREAD

**Issue by green-slime** [ceres-solver/ceres-solver#1027] opened 2023-11-14 14:21 UTC
Sorry I've encountered a similar question as #921 . I am using ceres 2.1.0#4 with cuda 10.1.

The summary.FullReport() indicates that the 'dense linear algebra library' used is indeed CUDA, as shown in Figure 2. It appears to provide some acceleration, but not so prominent as I anticipated . However，although I can observe GPU usage from nvidia-smi, the task manager consistently shows that the GPU usage by the process remains almost at 0%. Furthermore, based on the results, it seems that the time taken for dense normal Cholesky with CUDA is longer than sparse normal Cholesky. (The Jacobian matrix is indeed a sparse matrix.） Is it possible for such a situation to occur? Could it be that I have not correctly invoked the CUDA methods? 

Figure 1 represents the dense linear algebra computation without CUDA, Figure 2 represents the dense computation with CUDA, and Figure 3 represents the sparse computation. 

Thanks so much for any help. 

![dense](https://github.com/ceres-solver/ceres-solver/assets/56833901/4ae0c722-9c80-4b86-a336-99edfdd237d5)

![dense_cuda](https://github.com/ceres-solver/ceres-solver/assets/56833901/f7d3b405-b3ae-4c42-b48b-b5f85508d54e)
![sparse](https://github.com/ceres-solver/ceres-solver/assets/56833901/c90a9e77-f136-4f51-adcf-7d5e3d5e7314)

**Comment by Torchmm** [comment] 2023-11-17 07:58
i meet the same problem, did you solve this?

**Comment by sandwichmaker** [comment] 2024-01-07 01:08
This is a tiny problem, using CUDA is actually going to be worse because of the overhead of transferring data between the CPU and the GPU.  The problem is so small that the GPU does not have to do any real work.

**Closed by sandwichmaker** 2024-01-07 01:08 UTC
