### ISSUE TITLE
Failed to build in Ubuntu18.04 docker container 

### ISSUE THREAD

**Issue by SylarZiling** [ceres-solver/ceres-solver#903] opened 2022-10-24 17:51 UTC
Hi, I am trying to build ceres-solver in a Ubuntu18.04 container, i also installed the glog with version 3.5.1 from apt-get install, however, the cmake file continue give me error about fiding glog. Can anyone provides any hints or help? Best 

### glog location: 
/usr/include/glog
/usr/include/glog/log_severity.h
/usr/include/glog/logging.h
/usr/include/glog/raw_logging.h
/usr/include/glog/stl_logging.h
/usr/include/glog/vlog_is_on.h

/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libglog.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libglog.pc

/usr/share/doc
/usr/share/doc/libgoogle-glog-dev
/usr/share/doc/libgoogle-glog-dev/copyright
/usr/lib/x86_64-linux-gnu/libglog.so

### cmake result: 
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_BIGOBJ
-- Performing Test HAVE_BIGOBJ - Failed
-- Looking for pow in m
-- Looking for pow in m - found
-- Detected Ceres version: 2.2.0 from /root/dependencies/ceres-solver/include/ceres/version.h
-- Detected available Ceres threading models: [CXX_THREADS, OPENMP, NO_THREADS]
-- Found Eigen version 3.3.4: /usr/lib/cmake/eigen3
-- Enabling use of Eigen as a sparse linear algebra library.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA version 11.1: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so;/usr/local/cuda/lib64/libcusolver.so;/usr/local/cuda/lib64/libcusparse.so
-- The CUDA compiler identification is NVIDIA 11.1.105
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- A library with BLAS API found.
-- Found LAPACK library: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so
-- A library with BLAS API found.
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS: /usr/include (found version "5.1.0") 
-- Looking for cholmod_metis
-- Looking for cholmod_metis - found
-- Found SuiteSparse: /usr/include/suitesparse (found suitable version "5.1.2", minimum required is "4.5.6") found components:  CHOLMOD SPQR Partition Config AMD CAMD CCOLAMD COLAMD 
-- Found SuiteSparse 5.1.2, building with SuiteSparse.
-- Building without Apple's Accelerate sparse support.
-- Found Google Flags (gflags) version 2.2.1: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
CMake Error at cmake/FindGlog.cmake:366 (target_include_directories):
  Cannot specify include directories for imported target "glog::glog".
Call Stack (most recent call first):
  CMakeLists.txt:420 (find_package)

CMake Error at cmake/FindGlog.cmake:367 (target_link_libraries):
  Cannot specify link libraries for target "glog::glog" which is not built by
  this project.
Call Stack (most recent call first):
  CMakeLists.txt:420 (find_package)

**Comment by alexsmac** [comment] 2022-10-24 18:10
Can you confirm what CMake version you are using, I am guessing that it is older than 3.11 which is when use of `target_include_directories()` for imported targets became legal (see [here](https://github.com/ginkgo-project/ginkgo/issues/234) for a reported of what I think is the same underlying issue, also on 18.04).

**Comment by SylarZiling** [comment] 2022-10-24 19:05
> 



> 
Hi Alexsmac, thank you for the quick response. Yes, i double checked, the cmake version is 3.10.2 from apt-get install cmake

**Comment by SylarZiling** [comment] 2022-10-24 19:39
> Can you confirm what CMake version you are using, I am guessing that it is older than 3.11 which is when use of `target_include_directories()` for imported targets became legal (see [here](https://github.com/ginkgo-project/ginkgo/issues/234) for a reported of what I think is the same underlying issue, also on 18.04).

Hi Alexsmac, do you have any recommend version of cmake, i installed the cmake 3.24.1, but have different error in make -j command. 

""" 
/root/dependency/ceres-solver/internal/ceres/cuda_vector.cc:55:3:   required from here
/usr/include/glog/logging.h:638:9: error: ambiguous overload for 'operator<<' (operand types are 'std::ostream {aka std::basic_ostream<char>}' and 'std::nullptr_t')
   (*os) << v;

CMakeFiles/Makefile2:154: recipe for target 'internal/ceres/CMakeFiles/ceres_internal.dir/all' failed
make[1]: *** [internal/ceres/CMakeFiles/ceres_internal.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alexsmac** [comment] 2022-10-25 08:54
This is a separate issue, specifically this one: https://github.com/google/glog/pull/641 which was fixed in glog in 2021, updating glog should fix it.  We can also implement a workaround for this in Ceres if the number of cases are small (which they appear to be).  I will also bump our minimum CMake version in master to reflect the changes we made after the 2.1 release which was the first issue you encountered.

Unless you need to use the master branch, the 2.1 release should work out of the box for you.  It's also worth noting that we only officially support the current and previous LTS versions, so 20.04 is now the minimum for master.  However, we will fix the issues you have encountered here as they are bugs that would affect 20.04+ too

**Comment by sandwichmaker** [comment] 2022-11-14 14:50
@alexsmac can this issue be closed?

**Comment by sandwichmaker** [comment] 2022-11-25 22:35
ping?

**Comment by sergiud** [comment] 2023-09-09 18:18
Given we no longer support Ubuntu 18.04 (as per 40c1a7e), the issue is obsolete.

**Closed by sergiud** 2023-09-09 18:18 UTC
