### ISSUE TITLE
Eigen warnings

### ISSUE THREAD

**Issue by sweeneychris** [ceres-solver/ceres-solver#188] opened 2015-12-11 19:37 UTC
I just upgraded to Eigen 3.2.7 (gcc 4.8.3 on Ubuntu 14.04) and, after rebuilding the master branch of Ceres, am getting lots of warnings about multiple definitions of an Eigen macro. The offending line is here: https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/schur_eliminator_impl.h#L46

This is a non-fatal compiler warning, so it is not a big deal to me but it does spit out 1 warning for every time that file is included (which is a lot, since all the generated files include it).

**Comment by jlblancoc** [comment] 2015-12-11 21:09
If you are sure it is not caused by Ceres itself, it would be a good idea for you to also report it upstream to Eigen authors [here](http://eigen.tuxfamily.org/index.php?title=Bugzilla).

**Comment by sandwichmaker** [comment] 2015-12-11 21:46
I know of this problem, we are re-working the previous patch to fix this.

**Comment by sandwichmaker** [comment] 2015-12-12 15:22
fixed on the master.

**Closed by sandwichmaker** 2015-12-12 15:22 UTC
