### ISSUE TITLE
Custom allocator support

### ISSUE THREAD

**Issue by ojura** [ceres-solver/ceres-solver#613] opened 2020-07-21 08:17 UTC
Hi, as far as I can see, Ceres is using the global `operator new` throughout the codebase, and the Eigen aligned operator for its internal `FixedArray`. How big of an undertaking would it be to be able to pass a custom (stateful) allocator to `Problem` 
(like the PMR from C++17) all and use it to perform allocations?

In my case, I am seeing large contention between different subsystems for the system allocator. One of the subsystems is using Ceres for pose estimation, and I would like to separate all allocations performed by Ceres into a dedicated arena.

**Comment by sandwichmaker** [comment] 2020-07-21 14:09
This is highly non-trivial and its not clear to me if its worth the effort. Arena allocation is a good idea when one is doing a lot of small allocations. Once the problem is built ceres tries to minimize allocations. The problem itself contains some memory which it allocates but the user is responsible for doing much of the allocation there too.

What is the size of the problem that you are trying to solve that memory allocation is a source of problems for you.

**Comment by ojura** [comment] 2020-07-22 11:15
Hi @sandwichmaker, thanks for a very quick response. Here is some background info (although I do not think it is important, you will see why later). When we are optimizing the pose in visual odometry, the number of 'reprojected point-to-fixed plane' correspondence cost functions is roughly around 3k. Since the structure of the problem is always the same, we construct it once and preallocate all the cost functions (and if necessary allocate more and add them to the problem).

When we have a new pose estimation problem to solve with a new set of correspondences, we update them in our existing allocated cost functions. We exposed the constant correspondence data in our cost function class to make it modifiable, and we keep a copy of the plain pointer to the allocated cost function object before passing it to the constructor of `ceres::AutoDiffCostFunction` when allocating it, so we can update the "constant" data in our cost function object with the new correspondences. For the unused but allocated cost functions, we have a "valid" flag we can toggle to make the cost function return zero. (You will probably say that we could also have removed the unused cost functions from the problem, this might have made it more numerically stable and possibly a bit faster, but this also seems to work fine.)

Here is the kicker. This works well on its own, and I actually have no issues with this setup in isolation. It is hitting 2-3x realtime on Linux, and somewhat slower on Windows (1.5-2.5x) which is a very annoying light motif in this story, but I would still say that it is good enough.

The problems start happening on Windows when we fire up a bunch of other threads doing other stuff, like global loop closure search, trajectory optimization, point cloud fusing and LOD streaming to/from HDD w/compression, cloud rendering and recalculating (when the trajectory is optimized). On Linux, it looks like space is being traded for speed by overcommiting (the process virtual memory grows to something like 30 GB, although the physical RAM usage is not that bad), and the performance drops a bit, but not catastrophically.

On Windows, I see more conservative behaviour: lower memory use, more heap housekeeping, but lower performance (I have seen it drop to as low as 20-30% realtime). The visual odometry, which is my responsibility, is actually a good citizen here; like I mentioned, I have tried to reuse all std::vector buffers and the Ceres problem itself to avoid using the global allocator as much as possible. However, without a custom allocator, I can not avoid global allocations for stuff like node-based STL containers and Ceres internals.

So it's not that the visual odometry thread or Ceres used therein are bad citizens allocation-wise; I think the problem is that there are other bad citizens (that I am not in control of) which are heavily using the system allocator. I have tried increasing the priority of the visual odometry thread, but I have not seen a big change. It looks like if you try talking to the system allocator while lower priority threads are heavily using it, you spend time waiting in kernel mode, and effectively get priority inversion.

All of this is still a bit speculation from my side based on what I have seen so far (and I admit that I have quite limited experience in performance-oriented software engineering). I would like to try to make the visual odometry thread not touch the system allocator at all to confirm the theory.

**Comment by sandwichmaker** [comment] 2020-07-31 21:44
@ojura Thank you for the details and my apologies for taking so long to reply. What you describe is a real problem but it is not clear to me if passing a custom allocator to ceres (which TBH is near impossible) will solve your problem. We do not do very many if any high frequency memory allocations inside ceres. You could use a custom allocator for constructing the cost function objects, which is where I suspect all your high frequency allocations come from.

**Comment by sandwichmaker** [comment] 2020-08-20 14:18
Going to close this, as there isn't anything actionable no our end right now.

**Closed by sandwichmaker** 2020-08-20 14:18 UTC
