### ISSUE TITLE
Failed when make test

### ISSUE THREAD

**Issue by RoronoaZA** [ceres-solver/ceres-solver#583] opened 2020-04-28 10:27 UTC
when I run make test output like this:
Total Test time (real) = 194.27 sec

The following tests FAILED:
	 45 - levenberg_marquardt_strategy_test (Failed)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
make: *** [test] Error 8

and 
./bin/levenberg_marquardt_strategy_test, log like this 
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from LevenbergMarquardtStrategy
[ RUN      ] LevenbergMarquardtStrategy.AcceptRejectStepRadiusScaling
[       OK ] LevenbergMarquardtStrategy.AcceptRejectStepRadiusScaling (0 ms)
[ RUN      ] LevenbergMarquardtStrategy.CorrectDiagonalToLinearSolver
/home/jiaqi.he/CLionProjects/CameraCal/ceres-solver-1.14.0/internal/ceres/levenberg_marquardt_strategy_test.cc:159: Failure
Actual function call count doesn't match EXPECT_CALL(log, Log(google::WARNING, _, HasSubstr("Failed to compute a step")))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] LevenbergMarquardtStrategy.CorrectDiagonalToLinearSolver (0 ms)
[----------] 2 tests from LevenbergMarquardtStrategy (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LevenbergMarquardtStrategy.CorrectDiagonalToLinearSolver
  how can I deal this problem? 
thanks

**Comment by sandwichmaker** [comment] 2020-04-28 11:50
Please share more details of your build and test setup.

**Comment by sandwichmaker** [comment] 2020-05-22 00:34
Closing because unreproducible, please reopen if you have more details to share.

**Closed by sandwichmaker** 2020-05-22 00:34 UTC
