### ISSUE TITLE
/tmp/build/80754af9/snappy_1649923748780/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so

### ISSUE THREAD

**Issue by WYKXD** [ceres-solver/ceres-solver#1099] opened 2024-09-11 08:31 UTC
28%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/generated/schur_eliminator_d_d_d.cc.o
[ 28%] Linking CXX static library ../../lib/libceres.a
[ 28%] Built target ceres
Scanning dependencies of target test_util
Scanning dependencies of target schur_eliminator_benchmark
Scanning dependencies of target small_blas_gemm_benchmark
Scanning dependencies of target invert_psd_matrix_benchmark
Scanning dependencies of target small_blas_gemv_benchmark
Scanning dependencies of target autodiff_benchmarks
Scanning dependencies of target denoising
Scanning dependencies of target autodiff_benchmarks_fast_math
[ 29%] Building CXX object internal/ceres/CMakeFiles/test_util.dir/evaluator_test_utils.cc.o
make[2]: *** \u6ca1\u6709\u89c4\u5219\u53ef\u5236\u4f5c\u76ee\u6807\u201c/tmp/build/80754af9/snappy_1649923748780/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so\u201d\uff0c\u7531\u201cbin/small_blas_gemv_benchmark\u201d \u9700\u6c42\u3002 \u505c\u6b62\u3002
make[2]: *** \u6b63\u5728\u7b49\u5f85\u672a\u5b8c\u6210\u7684\u4efb\u52a1....
make[2]: *** \u6ca1\u6709\u89c4\u5219\u53ef\u5236\u4f5c\u76ee\u6807\u201c/tmp/build/80754af9/snappy_1649923748780/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so\u201d\uff0c\u7531\u201cbin/schur_eliminator_benchmark\u201d \u9700\u6c42\u3002 \u505c\u6b62\u3002
make[2]: *** \u6b63\u5728\u7b49\u5f85\u672a\u5b8c\u6210\u7684\u4efb\u52a1....
make[2]: *** \u6ca1\u6709\u89c4\u5219\u53ef\u5236\u4f5c\u76ee\u6807\u201c/tmp/build/80754af9/snappy_1649923748780/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so\u201d\uff0c\u7531\u201cbin/autodiff_benchmarks\u201d \u9700\u6c42\u3002 \u505c\u6b62\u3002
make[2]: *** \u6b63\u5728\u7b49\u5f85\u672a\u5b8c\u6210\u7684\u4efb\u52a1....
[ 29%] Building CXX object internal/ceres/CMakeFiles/small_blas_gemv_benchmark.dir/small_blas_gemv_benchmark.cc.o
[ 29%] Building CXX object internal/ceres/CMakeFiles/invert_psd_matrix_benchmark.dir/invert_psd_matrix_benchmark.cc.o
make[2]: *** \u6ca1\u6709\u89c4\u5219\u53ef\u5236\u4f5c\u76ee\u6807\u201c/tmp/build/80754af9/snappy_1649923748780/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so\u201d\uff0c\u7531\u201cbin/small_blas_gemm_benchmark\u201d \u9700\u6c42\u3002 \u505c\u6b62\u3002
make[2]: *** \u6b63\u5728\u7b49\u5f85\u672a\u5b8c\u6210\u7684\u4efb\u52a1....
make[2]: *** \u6ca1\u6709\u89c4\u5219\u53ef\u5236\u4f5c\u76ee\u6807\u201c/tmp/build/80754af9/snappy_1649923748780/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so\u201d\uff0c\u7531\u201cbin/invert_psd_matrix_benchmark\u201d \u9700\u6c42\u3002 \u505c\u6b62\u3002
make[2]: *** \u6b63\u5728\u7b49\u5f85\u672a\u5b8c\u6210\u7684\u4efb\u52a1....
[ 29%] Building CXX object examples/CMakeFiles/denoising.dir/denoising.cc.o
[ 30%] Building CXX object internal/ceres/CMakeFiles/small_blas_gemm_benchmark.dir/small_blas_gemm_benchmark.cc.o
[ 30%] Building CXX object internal/ceres/autodiff_benchmarks/CMakeFiles/autodiff_benchmarks.dir/autodiff_benchmarks.cc.o
make[2]: *** \u6ca1\u6709\u89c4\u5219\u53ef\u5236\u4f5c\u76ee\u6807\u201c/tmp/build/80754af9/snappy_1649923748780/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so\u201d\uff0c\u7531\u201cbin/autodiff_benchmarks_fast_math\u201d \u9700\u6c42\u3002 \u505c\u6b62\u3002
make[2]: *** \u6b63\u5728\u7b49\u5f85\u672a\u5b8c\u6210\u7684\u4efb\u52a1....
[ 30%] Building CXX object internal/ceres/CMakeFiles/schur_eliminator_benchmark.dir/schur_eliminator_benchmark.cc.o
[ 30%] Building CXX object internal/ceres/autodiff_benchmarks/CMakeFiles/autodiff_benchmarks_fast_math.dir/autodiff_benchmarks.cc.o
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/small_blas_gemv_benchmark.cc:81:6: warning: no previous declaration for \u2018void ceres::BM_MatrixVectorMultiply(benchmark::State&)\u2019 [-Wmissing-declarations]
   81 | void BM_MatrixVectorMultiply(benchmark::State& state) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/small_blas_gemv_benchmark.cc:97:6: warning: no previous declaration for \u2018void ceres::BM_MatrixTransposeVectorMultiply(benchmark::State&)\u2019 [-Wmissing-declarations]
   97 | void BM_MatrixTransposeVectorMultiply(benchmark::State& state) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/small_blas_gemm_benchmark.cc:89:6: warning: no previous declaration for \u2018void ceres::internal::BM_MatrixMatrixMultiplyDynamic(benchmark::State&)\u2019 [-Wmissing-declarations]
   89 | void BM_MatrixMatrixMultiplyDynamic(benchmark::State& state) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/small_blas_gemm_benchmark.cc:135:6: warning: no previous declaration for \u2018void ceres::internal::BM_MatrixTransposeMatrixMultiplyDynamic(benchmark::State&)\u2019 [-Wmissing-declarations]
  135 | void BM_MatrixTransposeMatrixMultiplyDynamic(benchmark::State& state) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/invert_psd_matrix_benchmark.cc:65:6: warning: no previous declaration for \u2018void ceres::internal::BenchmarkDynamicallyInvertPSDMatrix(benchmark::State&)\u2019 [-Wmissing-declarations]
   65 | void BenchmarkDynamicallyInvertPSDMatrix(benchmark::State& state) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/schur_eliminator_benchmark.cc:130:6: warning: no previous declaration for \u2018void ceres::internal::BM_SchurEliminatorEliminate(benchmark::State&)\u2019 [-Wmissing-declarations]
  130 | void BM_SchurEliminatorEliminate(benchmark::State& state) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/schur_eliminator_benchmark.cc:153:6: warning: no previous declaration for \u2018void ceres::internal::BM_SchurEliminatorBackSubstitute(benchmark::State&)\u2019 [-Wmissing-declarations]
  153 | void BM_SchurEliminatorBackSubstitute(benchmark::State& state) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/schur_eliminator_benchmark.cc:181:6: warning: no previous declaration for \u2018void ceres::internal::BM_SchurEliminatorForOneFBlockEliminate(benchmark::State&)\u2019 [-Wmissing-declarations]
  181 | void BM_SchurEliminatorForOneFBlockEliminate(benchmark::State& state) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/b203/\u4e0b\u8f7d/ceres-solver-2.0.0/internal/ceres/schur_eliminator_benchmark.cc:195:6: warning: no previous declaration for \u2018void ceres::internal::BM_SchurEliminatorForOneFBlockBackSubstitute(benchmark::State&)\u2019 [-Wmissing-declarations]
  195 | void BM_SchurEliminatorForOneFBlockBackSubstitute(benchmark::State& state)

Hello, may I ask how to solve this problem I encountered during the compilation process

**Comment by NeroBurner** [comment] 2024-09-12 06:13
please provide your system information (OS, compiler and compiler version used), info about the version of Ceres you want to compile, instructions on how to reproduce your error, etc. Everything that could help to pin down the problem

**Comment by sandwichmaker** [comment] 2024-09-20 16:09
Closing due to lack of information. Please reopen when you have more supporting info.

**Closed by sandwichmaker** 2024-09-20 16:09 UTC
