### ISSUE TITLE
FindTBB.cmake doesn't find newer TBB versions

### ISSUE THREAD

**Issue by NikolausDemmel** [ceres-solver/ceres-solver#612] opened 2020-07-18 17:05 UTC
For the intel provided linux binary installers, `FindTBB.cmake` has an outdated path, for gcc4.4 only:

https://github.com/ceres-solver/ceres-solver/blob/e39d9ed1d60dfeb58dd2a0df4622c683f87b28e3/cmake/FindTBB.cmake#L145-L157

Up to TBB 2020.2 it seems the possible versions of intel provided binary packages are: 4.1, 4.4, 4.7, 4.8

```
$ find /opt/intel/ -type d -name compilers_and_libraries* | grep 20........ -o | sort | uniq | tr '\n' ' '
2018.0.128 2018.2.199 2018.3.222 2018.5.274 2019.0.117 2019.1.144 2019.2.187 2019.3.199 2019.4.243 2019.5.281 2020.0.166 2020.1.217
$ find /opt/intel/ -type d -name gcc* | grep gcc... -o | sort | uniq | tr '\n' ' '
gcc4.1 gcc4.4 gcc4.7 gcc4.8
```

I can provide a patch adding all 4 possible paths. Of course that would break again in the future when newer TBB versions use newer paths... Not sure if there is a better solution. I don't think `PATH_SUFFIXES` can contain wildcards or something like that.

**Comment by sandwichmaker** [comment] 2020-07-21 14:13
@NikolausDemmel TBB is not used in ceres anymore.

**Comment by NikolausDemmel** [comment] 2020-07-21 14:54
It is here: https://github.com/ceres-solver/ceres-solver/blob/e39d9ed1d60dfeb58dd2a0df4622c683f87b28e3/cmake/FindSuiteSparse.cmake#L309

If TBB is not found at all, it's not a big deal. But the issue arises when I have system TBB (e.g. on Ubuntu via apt), and a newer binary install from Intel. Then even though I point it to the newer version, ceres finds the old libraries only, and exports together with suitesparse the old TBB libraries. This then conflicts with my main project (that uses ceres) linking to the newer (correct) TBB version.

**Comment by NikolausDemmel** [comment] 2020-07-21 14:56
(I don't know in which situations suitesparse actually depends on TBB. The current logic seems quite crude. Maybe it wouldn't be needed at all, at least for Ubuntu's suitesparse package.)

**Comment by alexsmac** [comment] 2020-07-23 16:12
Thanks @NikolausDemmel, I will have a look at this this weekend

**Comment by NikolausDemmel** [comment] 2020-07-23 16:46
Ok thanks. You can consider this patch if you want: https://github.com/NikolausDemmel/ceres-solver/commit/1497dfb86d4adabb094af16c7d6e39e0ca770aaa

**Comment by alexsmac** [comment] 2020-07-26 17:47
Hi @NikolausDemmel could you please try [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17560), I have replaced our (originally pulled from another external source) FindTBB.cmake with VTK's latest copy which includes a number of fixes, including I think for the issue that you raised.

**Comment by alexsmac** [comment] 2020-08-05 18:49
Closing as the CL has been merged into master ahead of the 2.0 release

**Comment by NikolausDemmel** [comment] 2020-08-05 18:54
Thanks for the fix. Sorry I couldn't try it yet. I'll check it out this weekend.

**Comment by NikolausDemmel** [comment] 2020-08-14 16:11
Finally I had a chance to test this. I think we might have to reopen the issue.

In general the updated FindTBB.cmake from VTK seems to be an improvement. In particular it better deals with debug and release libraries it seems. But it doesn't cover all cases properly, and it uses `TBB_ROOT` as a variable to specify which TBB to use, which causes issues with cmake, since for newer versions that variable has special meaning with `find_package`. Cmake then also outputs this warning:

```
CMake Warning (dev) at cmake/FindSuiteSparse.cmake:309 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    /opt/intel/tbb

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  CMakeLists.txt:283 (find_package)
```

I tested the following scenarios on Ubuntu 18.04 with the system version installed via apt (`libtbb-dev`, which is 2017) and a recent version installed from intel's apt repos (`intel-tbb-2020.2-102`) for 2.0.0rc and my patched version linked above. I added some output to ceres 2.0 to see the linked libraries that are picked up.

**1\. Only 2017 installed**

*ceres 2.0:*

```
-- Found Intel Thread Building Blocks (TBB) library (2017.0) assuming SuiteSparseQR was compiled with TBB.
-- TBB_LIBRARIES: optimized;/usr/lib/x86_64-linux-gnu/libtbb.so;debug;/usr/lib/x86_64-linux-gnu/libtbb.so
```

*my patch:*

```
-- Found Intel Thread Building Blocks (TBB) library (2017.0) assuming SuiteSparseQR was compiled with TBB
-- TBB_LIBRARIES: /usr/lib/x86_64-linux-gnu/libtbbmalloc.so;/usr/lib/x86_64-linux-gnu/libtbb.so
```

--> Both look fine: System version is picked up.






**2\. Only 2020 installed; TBBROOT/TBB_ROOT not specified**

*ceres 2.0:*

```
-- Found SUITESPARSEQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
```

*my patch:*

```
-- Found Intel Thread Building Blocks (TBB) library (2020.2) assuming SuiteSparseQR was compiled with TBB
-- TBB_LIBRARIES: /opt/intel/tbb/lib/intel64/gcc4.8/libtbb_preview.so;/opt/intel/tbb/lib/intel64/gcc4.8/libtbbmalloc.so;/opt/intel/tbb/lib/intel64/gcc4.8/libtbb.so
```

--> Mine picks up 2020 correctly; ceres 2.0 doesn't pick it up





**3\. Only 2020 installed; TBBROOT/TBB_ROOT env variable specified as `/opt/intel/tbb`**


*ceres 2.0:*

```
-- Found Intel Thread Building Blocks (TBB) library (2020.2) assuming SuiteSparseQR was compiled with TBB.
-- TBB_LIBRARIES: optimized;/opt/intel/tbb/lib/intel64/gcc4.8/libtbb.so;debug;/opt/intel/tbb/lib/intel64/gcc4.8/libtbb_debug.so
```

*my patch:*

*same as 2.*

--> both work fine






**4\. Both installed; TBBROOT/TBB_ROOT not specified**

*ceres 2.0:*

```
-- Found Intel Thread Building Blocks (TBB) library (2017.0) assuming SuiteSparseQR was compiled with TBB.
-- TBB_LIBRARIES: optimized;/usr/lib/x86_64-linux-gnu/libtbb.so;debug;/usr/lib/x86_64-linux-gnu/libtbb.so
```

*my patch:*

```
-- Found Intel Thread Building Blocks (TBB) library (2017.0) assuming SuiteSparseQR was compiled with TBB
-- TBB_LIBRARIES: /opt/intel/tbb/lib/intel64/gcc4.8/libtbb_preview.so;/usr/lib/x86_64-linux-gnu/libtbbmalloc.so;/usr/lib/x86_64-linux-gnu/libtbb.so

[...]

CMake Warning at internal/ceres/CMakeLists.txt:378 (add_executable):
  Cannot generate a safe runtime search path for target
  inner_product_computer_test because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libtbbmalloc.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/intel/tbb/lib/intel64/gcc4.8
    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/intel/tbb/lib/intel64/gcc4.8

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  internal/ceres/CMakeLists.txt:442 (ceres_test)

This warning is for project developers.  Use -Wno-dev to suppress it.
```

--> my version says version 2017 if found, but picks up part of the 2020 libraries; ceres 2.0 behaves fine, defaulting to the system version





**5\. Both installed; TBBROOT/TBB_ROOT env variable specified as `/opt/intel/tbb`**

*ceres 2.0:*

```
-- Found Intel Thread Building Blocks (TBB) library (2017.0) assuming SuiteSparseQR was compiled with TBB.
-- TBB_LIBRARIES: optimized;/usr/lib/x86_64-linux-gnu/libtbb.so;debug;/opt/intel/tbb/lib/intel64/gcc4.8/libtbb_debug.so
```

*my patch:*

```
-- Found Intel Thread Building Blocks (TBB) library (2020.2) assuming SuiteSparseQR was compiled with TBB
-- TBB_LIBRARIES: /opt/intel/tbb/lib/intel64/gcc4.8/libtbb_preview.so;/opt/intel/tbb/lib/intel64/gcc4.8/libtbbmalloc.so;/opt/intel/tbb/lib/intel64/gcc4.8/libtbb.so
```

--> my version looks fine; ceres 2.0 doesn't properly pick up 2020 and mixes libraries


**Conclusion:**

I think starting from your patched version, we should change `TBB_ROOT` back to `TBBROOT` to avoid the cmake conflict / warning, and fix cases 2. and 5.

Should I look into it, or do you want to take a look first @alexsmac. Would be great to get this into 2.0.0. I think it can be classified as a bug fix, and returning to TBBROOT is restoring the 1.14 behaviour w.r.t. that variable (I doubt it is used by many people though, since the 1.14 FindTBB.cmake is also buggy with similar behaviour...)

**Comment by NikolausDemmel** [comment] 2020-08-17 16:59
PS: Here is a testing repository with ci jobs for all the cases above with ceres 2.0.0 rc (+ cmake output fix): https://gitlab.com/NikolausDemmel/ceres-test-deps/-/pipelines/178824483

**Comment by alexsmac** [comment] 2020-08-19 21:02
Thanks @NikolausDemmel, that's a really helpful and detailed update.

I think we should set the CMP0074 policy to the NEW behaviour (if it exists - our minimum CMake version: 3.5, does not include it - it was introduced only in CMake 3.12).  This would mimic what VTK are doing on modern versions of CMake, originally explicitly via cmake_policy(), but now implicitly via cmake_minimum_required(VERSION) which calls cmake_policy(VERSION) as well.  They are calling `cmake_minimum_required(VERSION 3.12...3.16)` which means that they are setting CMP0074 to NEW, which means that the TBB_ROOT var *would* be used which I think is actually the intended behaviour.

TBH, I don't think that the wording of CMP0074 is very clear, but I think (and given that VTK is a primary Kitware project, it is very likely) that VTK's FindTBB is compliant with CMP0074 (i.e. NEW) - they are never actually setting TBB_ROOT, but they are referencing it - albeit in a way that is compliant with it's new usage.  It's unusual, as it the docs appear to suggest they should never be using it, but it doesn't look incompatible.

I think the issue here is actually not really to do with TBB_ROOT per-se, it's that the modern FindTBB does not specify a default search directory of: `/opt/intel/tbb` and our original FindTBB did.  However, relying on the existence of `TBB_ROOT` does appear to be inline with the Intel docs (and other client projects that use TBB).

As a result of all this, I think we should probably do the following:

1. Set CMP0074 to NEW if it exists:

```
if (POLICY CMP0074)
  cmake_policy(CMP0074 NEW)
endif()
```

I think the fact that this was implicitly set to the OLD policy, and was then ignored may actually be the reason for the failure in case 5) above.

2. Update the docs and maybe output a message() to specify that `TBB_ROOT` should be specified to force which version of TBB is used.

**Comment by NikolausDemmel** [comment] 2020-08-20 11:39
Thanks for looking into it again!

> I think we should set the CMP0074 policy to the NEW behaviour (if it exists - our minimum CMake version: 3.5, does not include it - it was introduced only in CMake 3.12). This would mimic what VTK are doing on modern versions of CMake, originally explicitly via cmake_policy(), but now implicitly via cmake_minimum_required(VERSION) which calls cmake_policy(VERSION) as well. They are calling cmake_minimum_required(VERSION 3.12...3.16) which means that they are setting CMP0074 to NEW, which means that the TBB_ROOT var would be used which I think is actually the intended behaviour.
>
> TBH, I don't think that the wording of CMP0074 is very clear, but I think (and given that VTK is a primary Kitware project, it is very likely) that VTK's FindTBB is compliant with CMP0074 (i.e. NEW) - they are never actually setting TBB_ROOT, but they are referencing it - albeit in a way that is compliant with it's new usage. It's unusual, as it the docs appear to suggest they should never be using it, but it doesn't look incompatible.

Agreed on setting CMP0074 to NEW if it exists. This allows people that use newer cmake to e.g. set the `Eigen3_ROOT` to more selectively guide cmake to a specific version of Eigen3 (rather than using `CMAKE_PREFIX_PATH`, which may affect other libraries as well).

However, I don't think it influences out `find_package(TBB)` call, since this uses find module mode, which even with CMP0074 NEW doesn't consider the TBB_ROOT variable by itself (only if the find-module handles it explicitly). The automatic handling added in cmake 3.12 seems to only extend to config mode of `find_package` (see [docs](https://cmake.org/cmake/help/v3.18/command/find_package.html#search-procedure)). So I disagree with this:

> I think the fact that this was implicitly set to the OLD policy, and was then ignored may actually be the reason for the failure in case 5) above.

I will test it and report back. But I think to fix case 5), we need to dig into the TBB find module and check why the paths are mixed up. (PS: I just realized that possibly the NEW behaviour could fix it, since it's mentioned in the docs the setting TBB_ROOT also affects recursive find... calls inside the package config. Maybe this part is true also for find modules. Let's see what the test shows.)

But I agree with your assessment, that the way the TBB find module handles TBB_ROOT is in the "same spirit" as the "CMP0074 NEW" behaviour for config mode, so I'm fine with leaving it as is in combination with setting CMP0074 to NEW, which should avoid the warning (even if the cmake docs seem to discourage usage of TBB_ROOT in find modules, as you have also pointed out).

> I think the issue here is actually not really to do with TBB_ROOT per-se, it's that the modern FindTBB does not specify a default search directory of: /opt/intel/tbb and our original FindTBB did. However, relying on the existence of TBB_ROOT does appear to be inline with the Intel docs (and other client projects that use TBB).

Ok, I haven't read the intel docs. I would find it a bit unfortunate if /opt/intel/tbb is not a default search path (lower prio than /usr), given that the intel binary packages always install it there. But if that is the consensus I'm also fine with requiring TBB_ROOT set to fix my case 2) above.

> Update the docs and maybe output a message() to specify that TBB_ROOT should be specified to force which version of TBB is used.

Yes, both are great suggestions.

**Comment by NikolausDemmel** [comment] 2020-08-20 11:52
Update: Setting the policy to NEW does not change how 5) behaves. I think we need to dig into the find module and how TBB_ROOT affects the search paths, to make sure the results are only taken from a single place, and installations are not mixed up like now. If we fix the find module, we can also submit it upstream with VTK.

See: https://gitlab.com/NikolausDemmel/ceres-test-deps/-/jobs/695599578

**Comment by sandwichmaker** [comment] 2020-08-31 16:53
whats the plan here? I'd like to resolve this soonish as this is a blocking issue for 2.0

**Comment by alexsmac** [comment] 2020-08-31 18:33
OK, so the issue is really that not all TBB releases include the debug libraries, so when these lines get executed:
```
find_library(TBB_LIBRARY_RELEASE
             NAMES ${TBB_LIBRARY_NAMES}
             PATHS ${TBB_LIB_SEARCH_PATH})
find_library(TBB_LIBRARY_DEBUG
             NAMES ${TBB_LIBRARY_NAMES_DEBUG}
             PATHS ${TBB_LIB_SEARCH_PATH})
```
they can find *different* directories within any of the paths listed in `TBB_LIB_SEARCH_PATH`, this would depend on the ordering and content of each.  The issue is that if the build is local, then on MSVC at least it will have a single build type per directory with different Release & Debug directories which means we can't necessarily just force the debug search to only occur in the same directory as the release library is found.  That would resolve this issue, but it might break other setups.

We could also add every `NO_XXX` qualifier to `find_library()` & `find_path()` if TBB_ROOT was specified, which should remove the possibility of finding anything else, even if TBB_ROOT does not exist.  However, this still doesn't prevent the previous issue from happening when TBB_ROOT is *not* specified if there are multiple TBB installs in the default search paths.

I think I favour the latter option, and then beyond that this is the user's own responsibility.  If they specify it exactly, they should get what they ask for, if they don't and they have multiple installs on the default search path then frankly they are doing something wrong and there is no reasonable expectation that Ceres should have to deal with determining which is the 'right' install to use.

**Comment by NikolausDemmel** [comment] 2020-08-31 21:25
> they can find different directories within any of the paths listed in TBB_LIB_SEARCH_PATH, this would depend on the ordering and content of each. The issue is that if the build is local, then on MSVC at least it will have a single build type per directory with different Release & Debug directories which means we can't necessarily just force the debug search to only occur in the same directory as the release library is found. That would resolve this issue, but it might break other setups.

We could enforce the same directories only on Unix (ideally same prefix as the found include directories), where I think it's a reasonable / robust way to find the libraries. But I understand that complicates the logic, so maybe not worth it.

> We could also add every NO_XXX qualifier to find_library() & find_path() if TBB_ROOT was specified, which should remove the possibility of finding anything else, even if TBB_ROOT does not exist. 

While this would then behave different from the the (newly) built in _ROOT variables in cmake, IMHO it would be fine. To me it's reasonable to assume that the user want's exactly the specified version, if TBB_ROOT is set.

> I think I favour the latter option, and then beyond that this is the user's own responsibility. If they specify it exactly, they should get what they ask for, if they don't and they have multiple installs on the default search path then frankly they are doing something wrong and there is no reasonable expectation that Ceres should have to deal with determining which is the 'right' install to use.

Sounds good to me as a reasonable tradeoff of effort and flexibility. So we'd call case 2. above a won't-fix and say ppl need to set TBB_ROOT if they want to use TBB from intel's binary packages.

**Comment by alexsmac** [comment] 2020-09-01 09:27
OK, updated CL is [here](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17720) after looking at the structure of the TBB releases for all platforms, I think we can enforce that the release & debug libraries should all live in the same directory.

**Comment by sandwichmaker** [comment] 2020-09-03 19:46
Fixed at head.

**Closed by sandwichmaker** 2020-09-03 19:46 UTC
