### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by CerrieJ** [ceres-solver/ceres-solver#299] opened 2017-07-05 10:51 UTC
Hi, I was trying to use Problem object and one of its method AddResidualBlock(), but I encountered a memory leak issue.

```
ResidualBlockId AddResidualBlock(CostFunction* cost_function,
                                   LossFunction* loss_function,
                                   double* x0);
```

If I did not release one of its parameters ,*cost_function, it will give me a memory leak warning. However, if in the end, I use delete command to release the memory, the program crashes.

```
	CostFunctor *coo = DBG_NEW CostFunctor;
	CostFunction* cost_function = DBG_NEW AutoDiffCostFunction<CostFunctor, 1, 1>(coo);
	problem.AddResidualBlock(cost_function, NULL, &x);

	// Run the solver!
	Solver::Options options;
	options.linear_solver_type = ceres::DENSE_QR;
	options.minimizer_progress_to_stdout = true;
	Solver::Summary summary;
	Solve(options, &problem, &summary);
	delete coo;
	delete cost_function;
```

memory leak：
![image](https://user-images.githubusercontent.com/15920960/27861502-b2539dd6-61b3-11e7-97ff-8b64e9718946.png)

crashe：
![error](https://user-images.githubusercontent.com/15920960/27861413-63a804f6-61b3-11e7-93eb-6d63262cc7b8.jpg)

**Comment by sandwichmaker** [comment] 2017-07-05 13:18
@CerrieJ the problem is not the lines you point out, but rather the delete lines in your code. AutoDiffCostFunction will take ownership of the functor passed to it and similarly Problem takes ownership of the CostFunction passed to it.  There should be no need to delete the functor or the costfunction.

**Comment by CerrieJ** [comment] 2017-07-06 02:24
@sandwichmaker 
Thanks for your answer. 
The reason why I use the delete function to release the functor and the costfunction memory is that I found the memory leaks at the line problem.AddResidualBlock() 
when I using the CRT Library to check my codes.  

 ```
problem.AddResidualBlock(DBG_NEW AutoDiffCostFunction<CostFunctor, 1, 1>(DBG_NEW CostFunctor), NULL, &x);
```  
Can you explain the reason for me?
Thanks.

**Comment by sandwichmaker** [comment] 2017-07-06 03:43
@CerrieJ I have no experience with development on windows/CRT. Maybe @alexsmac can say more or perhaps @Nazg-Gul ?

**Comment by Nazg-Gul** [comment] 2017-07-06 15:02
Not that much familiar with CRT either, but one thing seems specious to me. You are calling `_CrtDumpMemoryLeaks()` before `problem`'s destructor is called (problem will be destroyed when exiting current scope). This seems to explain both issues you'rte experiencing:

- `_CrtDumpMemoryLeaks()` will report memory leak because you've got objects which are still alife at the moment of `_CrtDumpMemoryLeaks()` call.
- If you manually free cost functor, `_CrtDumpMemoryLeaks()` will not report leak, but you'll have crash when actual `Problem::~Problem()` is called.

You should not be freeing cost functor, Problem is taking ownership over the pointer. Instead, you should change the way you detect memory leaks. Either move all the code into a scope, like

```
  int main() {
    {
      // All current solver logic goes here.
    }
    _CrtDumpMemoryLeaks();
    return;
  }
```

Or move solver-related things into a function, called form `main()`:
```
  static void mySolverStuff() {
    // Your problem solver goes here
  }
  int main() {
    mySolverStuff();
    _CrtDumpMemoryLeaks();
    return 0;
  }
```

Either of this ways will ensure problem's destructor is called prior to `_CrtDumpMemoryLeaks()` call.

**Comment by CerrieJ** [comment] 2017-07-07 07:49
@Nazg-Gul  Thanks for your explain. I'm so sorry for my mistake and I did not found it before my last reply. Last day I found I calling _CrtDumpMemoryLeaks() before problem's destructor is called and I modified it like your explain, there is my new codes:
```#define _CRTDBG_MAP_ALLOC
#include <ceres/ceres.h>
#include <cstdlib>
#include <crtdbg.h>

using namespace ceres;

#ifdef _DEBUG
#define DBG_NEW new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )
#else
#define DBG_NEW new
#endif


struct CostFunctor {
	template <typename T>
	bool operator()(const T* const x, T* residual) const {
		residual[0] = T(10.0) - x[0];
		return true;
	}
};

void mySolver()
{
	double initial_x = 5.0;
	double x = initial_x;

	Problem problem;

	CostFunction* cost_function = DBG_NEW AutoDiffCostFunction<CostFunctor, 1, 1>(DBG_NEW CostFunctor);
	problem.AddResidualBlock(cost_function, NULL, &x);

	Solver::Options options;
	options.linear_solver_type = ceres::DENSE_QR;
	options.minimizer_progress_to_stdout = true;
	Solver::Summary summary;
	Solve(options, &problem, &summary);
}

void main() {
	_CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) | _CRTDBG_LEAK_CHECK_DF);

	mySolver();

	_CrtDumpMemoryLeaks();
}
```
There is the  memory leak report:
```
Detected memory leaks!
Dumping objects ->
{322} normal block at 0x015AEE08, 8 bytes long.
 Data: < u a    > C0 75 B1 61 00 00 00 00 
{285} normal block at 0x015AEDC0, 8 bytes long.
 Data: <`u a    > 60 75 B1 61 00 00 00 00 
{280} normal block at 0x015AEC78, 8 bytes long.
 Data: < G a    > F0 47 B0 61 00 00 00 00 
{279} normal block at 0x015AEC30, 8 bytes long.
 Data: < G a    > C8 47 B0 61 00 00 00 00 
{278} normal block at 0x015AEBE8, 8 bytes long.
 Data: <LH a    > 4C 48 B0 61 00 00 00 00 
{271} normal block at 0x015AEBA0, 8 bytes long.
 Data: <   a    > 90 BE B0 61 00 00 00 00 
{264} normal block at 0x015AE548, 8 bytes long.
 Data: <   a    > EC BE B0 61 00 00 00 00 
{225} normal block at 0x015AE500, 8 bytes long.
 Data: <   a    > B0 BE B0 61 00 00 00 00 
{188} normal block at 0x015AE9F8, 8 bytes long.
 Data: <   a    > D0 BE B0 61 00 00 00 00 
Object dump complete.
```
If I didn't call my mySolver() function like this:
```
void main() {
	_CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) | _CRTDBG_LEAK_CHECK_DF);

	//mySolver();

	_CrtDumpMemoryLeaks();
}
```

 it still report me the memory leak:
```
Detected memory leaks!
Dumping objects ->
{322} normal block at 0x01CCEF50, 8 bytes long.
 Data: < u a    > C0 75 B1 61 00 00 00 00 
{285} normal block at 0x01CCEF08, 8 bytes long.
 Data: <`u a    > 60 75 B1 61 00 00 00 00 
{280} normal block at 0x01CCEDC0, 8 bytes long.
 Data: < G a    > F0 47 B0 61 00 00 00 00 
{279} normal block at 0x01CCED78, 8 bytes long.
 Data: < G a    > C8 47 B0 61 00 00 00 00 
{278} normal block at 0x01CCED30, 8 bytes long.
 Data: <LH a    > 4C 48 B0 61 00 00 00 00 
{271} normal block at 0x01CCECE8, 8 bytes long.
 Data: <   a    > 90 BE B0 61 00 00 00 00 
{264} normal block at 0x01CCE690, 8 bytes long.
 Data: <   a    > EC BE B0 61 00 00 00 00 
{225} normal block at 0x01CCE648, 8 bytes long.
 Data: <   a    > B0 BE B0 61 00 00 00 00 
{188} normal block at 0x01CCEB40, 8 bytes long.
 Data: <   a    > D0 BE B0 61 00 00 00 00 
Object dump complete.
```

If i comment out the contents of mySolver() function and I still call mySolver() in main function like this :
```
void mySolver()
{
	/*double initial_x = 5.0;
	double x = initial_x;

	Problem problem;

	CostFunction* cost_function = DBG_NEW AutoDiffCostFunction<CostFunctor, 1, 1>(DBG_NEW CostFunctor);
	problem.AddResidualBlock(cost_function, NULL, &x);

	Solver::Options options;
	options.linear_solver_type = ceres::DENSE_QR;
	options.minimizer_progress_to_stdout = true;
	Solver::Summary summary;
	Solve(options, &problem, &summary);*/
}

void main() {
	_CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) | _CRTDBG_LEAK_CHECK_DF);

	mySolver();

	_CrtDumpMemoryLeaks();
}
```
the memory leak warning disappear!

I‘m sorry for my so long statement.
Thanks again.

**Comment by CerrieJ** [comment] 2017-07-07 07:57
@sandwichmaker @Nazg-Gul 
Thanks both of you. I knew my question maybe a bit weird, maybe everything is because I'm not familiar with ceres solver and Windows/CRT, and I will study hard. So, If you not have any idea about my question please feel free to ignore it.

Thanks.

**Comment by Nazg-Gul** [comment] 2017-07-07 08:13
Since you've got `_CRTDBG_LEAK_CHECK_DF` flag passed to CRT debug flags, you don't have to explicitly call `_CrtDumpMemoryLeaks()`, it'll be called automatically at program exit. That could solve some false-positive leaks reports (there might be some heap allocations in some static objects from CRT itself or libraries used by Ceres).

In any case, i don't know specifics of leak detection on Windows/CRT, so you'd better consult MSDN or MSVC other related forums.

**Comment by sandwichmaker** [comment] 2017-07-10 22:20
I am going to close this issue as this looks like a MSVC thing rather than a ceres issue.

**Closed by sandwichmaker** 2017-07-10 22:20 UTC
