### ISSUE TITLE
CMake Warning (dev) in internal/ceres/CMakeLists.txt:

### ISSUE THREAD

**Issue by mallareddy47** [ceres-solver/ceres-solver#851] opened 2022-08-06 19:41 UTC
CMake Warning (dev) in internal/ceres/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "ceres_cuda_kernels".
This warning is for project developers.  Use -Wno-dev to suppress it.

Hello Team,

Im running ceres-solver for my COLMAP in COLAB and facing above issue while executing below script. Any help would appreciate. is it just a warning or does it cause any issue for COLMAP to run?

!sudo apt-get install libatlas-base-dev libsuitesparse-dev
!git clone https://ceres-solver.googlesource.com/ceres-solver
%cd ceres-solver
!git checkout $(git describe --tags) # Checkout the latest release
%mkdir build
%cd build
!cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
!make
!sudo make install

Thanks,
Mallareddy.

**Comment by sergiud** [comment] 2022-08-06 20:01
What issue are you facing exactly?

In case the warning is bothering you, just set `CMAKE_CUDA_ARCHITECTURES` manually. You can also disable CUDA altogether by setting `-DUSE_CUDA=OFF`.

@joydeep-b CMake 3.18 introduced the `CMP0104` policy whose `NEW` behavior is to auto initialize `CUDA_ARCHITECTURES`. Ceres should probably enable the policy if it's available.

**Comment by joydeep-b** [comment] 2022-08-06 20:34
Yes, I have seen this. 
The issue is that starting CMake 3.18, we need to specify a list of Cuda virtual/real architectures, but this is not supported on older CMake versions. 
The version of CMake that ships with Ubuntu 20.04 does not support this feature.
@sandwichmaker Let's mark this as an issue to investigate by the next minor revision. I'll take a look at it by then.

**Comment by joydeep-b** [comment] 2022-08-09 04:08
This has been fixed by d8dad14eed1cd162526277b08012a2f82024098b

**Comment by mallareddy47** [comment] 2022-08-13 00:01
@joydeep-b is this moved to master branch? or diff branch

**Comment by joydeep-b** [comment] 2022-08-13 04:07
This is merged into master.
@sandwichmaker  this issue can be closed.

**Closed** 2022-08-13 04:11 UTC
Labels: bug
