### ISSUE TITLE
(covariance_test) Link error LNK2019 in VisualStudio2013 x64

### ISSUE THREAD

**Issue by shengyenlo** [ceres-solver/ceres-solver#226] opened 2016-09-09 09:17 UTC
When I build the covariance_test code on VS2013 x64, it got the link errors that i cannot resolve:

`Error 1 error LNK2019: unresolved external symbol "__int64 __cdecl SuiteSparseQR<double>(int,double,__int64,struct cholmod_sparse_struct *,struct cholmod_sparse_struct * *,__int64 * *,struct cholmod_common_struct *)" (??$SuiteSparseQR@N@@YA_JHN_JPEAUcholmod_sparse_struct@@PEAPEAU0@PEAPEA_JPEAUcholmod_common_struct@@@Z) referenced in function "public: bool __cdecl ceres::internal::CovarianceImpl::ComputeCovarianceValuesUsingSuiteSparseQR(void)" (?ComputeCovarianceValuesUsingSuiteSparseQR@CovarianceImpl@internal@ceres@@QEAA_NXZ))	covariance_test
`

`Error	2	error LNK2019: unresolved external symbol cholmod_l_gpu_deallocate referenced in function cholmod_l_free_work)	covariance_test
`

Any help will be appreciated. 
Thanks.

**Comment by alexsmac** [comment] 2016-09-09 09:38
Interesting - @sandwichmaker this looks a but suspicious, covariance_impl.cc is using the cholmod_l_xxx() functions, and SuiteSparse_long - which actually only exists if SuiteSparse is compiled with DLONG defined s/t it uses <double, int64> for values/indices when the default is <double, int32>.  ComputeCovarianceValuesUsingSuiteSparseQR() in covariance_impl.cc should be using the non "_l_" prefixed versions and not SuiteSparse_long shouldn't it?

**Comment by sandwichmaker** [comment] 2016-09-09 11:31
No this is a quirk of SuiteSparseQR which only uses matrices with long indices, so our use of cholmod_l_* functions is correct. AFAIK SuiteSparse builds with the regular integer and the long variant.

**Comment by alexsmac** [comment] 2016-09-09 12:57
@shengyenlo - the problem is that your build of SuiteSparse was not built with DLONG defined, as Sameer says that should be part of the default build configuration.

**Comment by sandwichmaker** [comment] 2016-09-25 02:38
Closing as this is not a ceres issue.

**Closed by sandwichmaker** 2016-09-25 02:38 UTC
