### ISSUE TITLE
Error in evaluating the ResidualBlock

### ISSUE THREAD

**Issue by 44825762** [ceres-solver/ceres-solver#801] opened 2022-05-09 15:40 UTC
I use Ceres to optimise a non-linear problem, but it shows this error.

It is very weird, I checked the jacobian and the residuals, they all correct.

I can't understand where is the error comes from.

Here is a part of log.

The error is not caused by  "Uninitialized".

I am looking forward to your reply.

Thank you.

================================
   res     0.723307   0.397519    1.07305  -0.825167 -0.0501836  -0.562656
jac
  3.0071e-05            0            0            0            0            0
-1.33713e-06    3.224e-05            0            0            0            0
 -5.5532e-06 -1.49396e-06  3.00939e-05            0            0            0
-9.57822e-08   1.7439e-06  -8.4219e-07  5.87996e-06            0            0
-2.17407e-06 -2.53591e-07  1.44578e-06   7.4504e-07  6.47146e-06            0
 1.45034e-06 -1.57725e-06 -2.91756e-07 -2.34769e-07 -1.85578e-07  6.30806e-06
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0509 23:04:07.611050 11797 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 2 parameter blocks x 6 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:         0.723307     0.397519      1.07305    -0.825167   -0.0501836    -0.562656 

Parameter Block 0, size: 7

   0.0271139 |   3.0071e-05    3.224e-05  3.00939e-05  5.87996e-06  6.47146e-06  6.30806e-06 
    0.024274 |            0            0            0            0            0 Uninitialized 
   0.0265459 |            0            0            0            0  1.45034e-06 Uninitialized 
    0.818717 |            0            0            0 -2.17407e-06 -1.57725e-06 Uninitialized 
  -0.0376479 |            0            0 -9.57822e-08 -2.53591e-07 -2.91756e-07 Uninitialized 
    0.571767 |            0  -5.5532e-06   1.7439e-06  1.44578e-06 -2.34769e-07 Uninitialized 
   0.0369805 | -1.33713e-06 -1.49396e-06  -8.4219e-07   7.4504e-07 -1.85578e-07 Uninitialized 

Parameter Block 1, size: 7

    0.670625 | Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized 
    0.426507 | Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized 
     1.00633 | Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized 
   -0.816469 | Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized 
   0.0302407 | Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized 
   -0.574071 | Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized 
   0.0539041 | Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized Uninitialized 

E0509 23:04:07.611131 11797 trust_region_minimizer.cc:72] Terminating: Residual and Jacobian evaluation failed.

Solver Summary (v 1.14.0-eigen-(3.3.4)-lapack-suitesparse-(5.1.2)-cxsparse-(3.1.9)-eigensparse-openmp-no_tbb)

                                     Original                  Reduced
Parameter blocks                           26                       26
Parameters                                182                      182
Effective parameters                      181                      181
Residual blocks                            50                       50
Residuals                                 300                      300

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy                  DOGLEG (TRADITIONAL)

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver ordering              AUTOMATIC                     25,1
Schur structure                         6,7,6                    d,d,d

Cost:
Initial                         -1.000000e+00

Minimizer iterations                        0
Successful steps                            0
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                         0.000174

  Residual only evaluation           0.000000 (0)
  Jacobian & residual evaluation     0.000206 (1)
  Linear solver                      0.000000 (0)
Minimizer                            0.000224

Postprocessor                        0.000005
Total                                0.000404

Termination:                          FAILURE (Residual and Jacobian evaluation failed.)

**Comment by sandwichmaker** [comment] 2022-05-09 19:33
How do you know your jacobians are correct? can you post the code thats computing it?

**Comment by 44825762** [comment] 2022-05-11 10:32
Problem solved.

It does cause by jacobian.

Here is the solution.

Before we put the jacobian into ceres, we should add a column with zero in jacobian.

For example, assume the jacobian size is 6x6, we should make it to 6x7.

Thanks.

**Comment by sandwichmaker** [comment] 2022-05-11 12:06
That makes no sense.

**Comment by sandwichmaker** [comment] 2023-09-28 22:25
Closing because the issue is too old.

**Closed by sandwichmaker** 2023-09-28 22:25 UTC
