### ISSUE TITLE
Access violation error in NumericDiffCostFunction constructor in VS2017 debug mode

### ISSUE THREAD

**Issue by maria-korosteleva** [ceres-solver/ceres-solver#454] opened 2019-01-25 02:49 UTC
I encounter an Access violation exception when compiling the program that uses NumericDiffCostFunction/AutoDiffCostFunction in Debug mode in Visual Studio 2017. The exeption seems to occur inside the object constructor

Here is the minimized code that reproduces the problem.
```
#include "pch.h"
#include "ceres/ceres.h"
using ceres::AutoDiffCostFunction;
using ceres::NumericDiffCostFunction;
using ceres::CostFunction;

class blaFunctor
{
public:
    blaFunctor() {};
    ~blaFunctor() {};

    bool operator()(const double * const x, double * residual) const
    {
        residual[0] = x[0];
        return true;
    }
};

int main()
{
    NumericDiffCostFunction<blaFunctor, ceres::CENTRAL, 1, 1> F(new blaFunctor);
}
```
The exception is as such: 
"Exception thrown at 0x00007FF64C66D6DD in main.exe: 0xC0000005: Access violation writing location 0x0000000000000000."

The screenshot with the call stack
![2019-01-25_11-41_c](https://user-images.githubusercontent.com/6837635/51721847-b7106900-2096-11e9-9ac0-ad8a86f7be47.jpg)

I'm using Ceres v1.14. The library was built in Release mode (if it matters). File pch.h is empty

**Comment by sandwichmaker** [comment] 2019-02-07 07:56
@maria-korosteleva sorry for taking this long. Something weird is going on with msvc here. Because I am unable to replicate the problem on my end. But more importantly, line 77 in sized cost function should not get executed since N2 is zero.

Are you able to use the latest upstream version instead?

**Comment by sandwichmaker** [comment] 2019-02-07 07:57
I mean N1.

**Comment by maria-korosteleva** [comment] 2019-02-08 04:18
@sandwichmaker, thank you for your answer.

> Are you able to use the latest upstream version instead?

I tried to run the same program with the latest upstream version of ceres just now. 
This time it fails in the destructor with a different error:

![2019-02-08_13-11](https://user-images.githubusercontent.com/6837635/52458540-565b5300-2ba3-11e9-8df4-8ef86e0deffb.jpg)

Running in Release mode is fine as before

**Comment by maria-korosteleva** [comment] 2019-02-12 07:37
@sandwichmaker, regarding your note:
> @maria-korosteleva sorry for taking this long. Something weird is going on with msvc here. Because I am unable to replicate the problem on my end. But more importantly, line 77 in sized cost function should not get executed since N2 is zero.
> 

I've rechecked: it turns out that while I was trying to figure out what's going on, I've accidentally added a blank line to the header. So it fails on line 76 (not 77) of SizedCostFunction.h, the first time the CERES_ADD_PARAMETER_BLOCK() is executed

I'm sorry for the misunderstanding that occurred from this

**Comment by sandwichmaker** [comment] 2019-03-03 19:08
I am wondering if this is a lifetime issue, since you are creating this function on the stack.
what happens if you do

auto cost_function  = new NumericDiffCostFunction<blaFunctor, ceres::CENTRAL, 1, 1> (new blaFunctor);
delete cost_function;

do you get the same problem?

**Comment by maria-korosteleva** [comment] 2019-03-07 04:45
Yes, I get the same problem for creation on the heap too: "An invalid parameter was passed to a function that considers invalid parameters fatal". Just tried with the version of ceres I had at the beginning of the Feb. 

Reproduces for the dynamic allocation with stable release (ceres-1.14.0) as well.

**Comment by sandwichmaker** [comment] 2019-03-07 05:42
@maria-korosteleva can you share your latest code which produces the violation?

**Comment by maria-korosteleva** [comment] 2019-03-07 07:42
Sure
```
#include "pch.h"
#include "ceres/ceres.h"

class blaFunctor
{
public:
    blaFunctor() {};
    ~blaFunctor() {};

    bool operator()(const double * const x, double * residual) const
    {
        residual[0] = x[0];
        return true;
    }
};

int main()
{
    auto cost_function = new ceres::NumericDiffCostFunction<blaFunctor, ceres::CENTRAL, 1, 1>(new blaFunctor);
    delete cost_function;
}
```

**Comment by sandwichmaker** [comment] 2019-03-07 12:52
@maria-korosteleva the only difference I observe in the code I compile and the on you are compiling is the presence of pch.h. Since I am not using visual studio, what happens if you remove pch.h? I wonder if precompiled headers are not mixing well with template code in ceres?

**Comment by maria-korosteleva** [comment] 2019-03-09 03:49
@sandwichmaker
I turned off the use of the pre-compiled headers. The result didn't change, unfortunately

**Comment by sandwichmaker** [comment] 2019-03-10 14:40
Thank you for your patience @maria-korosteleva, I do not have a windows compiler and nothing on the clang compiler toolchain replicates this :/

**Comment by maria-korosteleva** [comment] 2019-03-14 01:37
@sandwichmaker ok, thank you for trying to help me.
The issue doesn't block my work entirely, and since I'm the only one complaining about it right now, I guess, it doesn't worth further investigation.

**Comment by sandwichmaker** [comment] 2019-03-14 08:10
I am sorry I could not help you more @maria-korosteleva . I am going to close this for now. If you have more information/reproduction info, please feel free to re-open it.

**Closed by sandwichmaker** 2019-03-14 08:10 UTC
