### ISSUE TITLE
cubic_interpolation_test.cc causes an internal error in msvc 2013

### ISSUE THREAD

**Issue by dtmoodie** [ceres-solver/ceres-solver#167] opened 2015-07-07 22:07 UTC
1>------ Build started: Project: cubic_interpolation_test, Configuration: Debug x64 ------
1>  cubic_interpolation_test.cc
1>G:\ceres-solver\include\ceres/cubic_interpolation.h(180): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'msc1.cpp', line 1325)
1>   To work around this problem, try simplifying or changing the program near the locations listed above.
1>  Please choose the Technical Support command on the Visual C++ 
1>   Help menu, or open the Technical Support help file for more information
1>          G:\ceres-solver\include\ceres/cubic_interpolation.h(142) : while compiling class template member function 'bool ceres::CubicInterpolator<ceres::Array1D<double,2,true>>::Evaluate(double,double *,double *) const'
1>          G:\ceres-solver\internal\ceres\cubic_interpolation_test.cc(241) : see reference to function template instantiation 'bool ceres::CubicInterpolator<ceres::Array1D<double,2,true>>::Evaluate(double,double *,double *) const' being compiled
1>          G:\ceres-solver\internal\ceres\cubic_interpolation_test.cc(237) : see reference to class template instantiation 'ceres::CubicInterpolator<ceres::Array1D<double,2,true>>' being compiled
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

CMake config:
-- Found Eigen version 3.2.2: E:/libs/eigen/include/eigen3

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

A library with BLAS API found.
-- Found LAPACK library: G:/suitesparse-metis-for-windows/lapack_windows/x64/liblapack.lib;G:/suitesparse-metis-for-windows/lapack_windows/x64/libblas.lib
-- Found BLAS library: G:/suitesparse-metis-for-windows/lapack_windows/x64/libblas.lib
A library with BLAS API found.
Found AMD library: E:/LIBS/suitesparse/lib64/libamdd.lib
Found AMD header in: E:/LIBS/suitesparse/include/suitesparse
Found CAMD library: E:/LIBS/suitesparse/lib64/libcamdd.lib
Found CAMD header in: E:/LIBS/suitesparse/include/suitesparse
Found COLAMD library: E:/LIBS/suitesparse/lib64/libcolamdd.lib
Found COLAMD header in: E:/LIBS/suitesparse/include/suitesparse
Found CCOLAMD library: E:/LIBS/suitesparse/lib64/libccolamdd.lib
Found CCOLAMD header in: E:/LIBS/suitesparse/include/suitesparse
Found CHOLMOD library: E:/LIBS/suitesparse/lib64/libcholmodd.lib
Found CHOLMOD header in: E:/LIBS/suitesparse/include/suitesparse
Found SuiteSparseQR library: E:/LIBS/suitesparse/lib64/libspqrd.lib
Found SuiteSparseQR header in: E:/LIBS/suitesparse/include/suitesparse
Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
Found SuiteSparse_config library: E:/LIBS/suitesparse/lib64/suitesparseconfigd.lib
Found SuiteSparse_config header in: E:/LIBS/suitesparse/include/suitesparse
Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse 4.4.4, building with SuiteSparse.
-- Found CXSparse version: 3.1.4, building with CXSparse.
-- Found Google Flags header in: E:/libs/gflags/include, in namespace: gflags
-- Found Google Log header in: E:/libs/glog/include
-- Building with OpenMP.
-- Found unordered_map/set in std namespace.
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a shared library.
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
Enabling CERES_USING_SHARED_LIBRARY in Ceres config.h

Additional info:
Debug and Release mode, only tested with 64bit compilation.
Suitesparse compiled without Metis.

**Comment by sandwichmaker** [comment] 2015-07-08 05:14
I do not use windows so I cannot reproduce this bug, so some help isolating this bug would be useful.
Is it possible for you to strip down cubic_interpolation_test.cc down till you have the minimum possible code that will replicate this crash and share it with us?

**Comment by sandwichmaker** [comment] 2015-07-08 05:14
@alexsmac @keir any further ideas?

**Comment by alexsmac** [comment] 2015-07-08 08:51
Looks like a bug in MSVC: https://forum.kde.org/viewtopic.php?f=74&t=120554

**Comment by sandwichmaker** [comment] 2015-07-21 14:33
I am not sure what we can do on this front. so I am going to go ahead and close this bug. Please feel free to open it, if there is something actionable that ceres developers can do.

**Closed** 2015-07-21 14:34 UTC
Labels: bug, wontfix
