### ISSUE TITLE
Tests cubic_interpolation_test on ubuntu 14.04 i386 fails

### ISSUE THREAD

**Issue by NeroBurner** [ceres-solver/ceres-solver#212] opened 2016-06-14 09:08 UTC
I'm trying to do a 32bit build of ceres-solver version 1.11.0

installed build dependencies: cmake, libgoogle-glog-dev, libatlas-base-dev, libeigen3-dev, libsuitesparse-dev

builds fine on ubuntu 14.04 amd64

building on ubuntu 14.04 i386 produces an error at the tests
```
      Start 18: cubic_interpolation_test
18/67 Test #18: cubic_interpolation_test ....................***Exception: Other  0.09 sec
[==========] Running 23 tests from 6 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from Grid1D
[ RUN      ] Grid1D.OneDataDimension
[       OK ] Grid1D.OneDataDimension (0 ms)
[ RUN      ] Grid1D.OneDataDimensionOutOfBounds
[       OK ] Grid1D.OneDataDimensionOutOfBounds (0 ms)
[ RUN      ] Grid1D.TwoDataDimensionIntegerDataInterleaved
[       OK ] Grid1D.TwoDataDimensionIntegerDataInterleaved (0 ms)
[ RUN      ] Grid1D.TwoDataDimensionIntegerDataStacked
[       OK ] Grid1D.TwoDataDimensionIntegerDataStacked (0 ms)
[----------] 4 tests from Grid1D (0 ms total)

[----------] 6 tests from Grid2D
[ RUN      ] Grid2D.OneDataDimensionRowMajor
[       OK ] Grid2D.OneDataDimensionRowMajor (0 ms)
[ RUN      ] Grid2D.OneDataDimensionRowMajorOutOfBounds
[       OK ] Grid2D.OneDataDimensionRowMajorOutOfBounds (0 ms)
[ RUN      ] Grid2D.TwoDataDimensionRowMajorInterleaved
[       OK ] Grid2D.TwoDataDimensionRowMajorInterleaved (0 ms)
[ RUN      ] Grid2D.TwoDataDimensionRowMajorStacked
[       OK ] Grid2D.TwoDataDimensionRowMajorStacked (0 ms)
[ RUN      ] Grid2D.TwoDataDimensionColMajorInterleaved
[       OK ] Grid2D.TwoDataDimensionColMajorInterleaved (0 ms)
[ RUN      ] Grid2D.TwoDataDimensionColMajorStacked
[       OK ] Grid2D.TwoDataDimensionColMajorStacked (0 ms)
[----------] 6 tests from Grid2D (0 ms total)

[----------] 3 tests from CubicInterpolatorTest
[ RUN      ] CubicInterpolatorTest.ConstantFunction
F0614 08:20:27.871011 12845 cubic_interpolation.h:72] Check failed: x >= 0.0 (-2.63678e-16 vs. 0) 
*** Check failure stack trace: ***
    @ 0x555ceefc  (unknown)
    @ 0x555cee13  (unknown)
    @ 0x555ce85f  (unknown)
    @ 0x555d18b0  (unknown)
    @  0x8071cdf  ceres::CubicHermiteSpline<>()
    @  0x8072136  ceres::internal::CubicInterpolatorTest::RunPolynomialInterpolationTest<>()
    @  0x806ba7c  ceres::internal::CubicInterpolatorTest_ConstantFunction_Test::TestBody()
    @  0x80a307c  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @  0x8093b4c  testing::Test::Run()
    @  0x8093c2d  testing::TestInfo::Run()
    @  0x8093dc7  testing::TestCase::Run()
    @  0x80940f7  testing::internal::UnitTestImpl::RunAllTests()
    @  0x8094469  testing::UnitTest::Run()
    @  0x806b88f  main
    @ 0x5575ca83  (unknown)
    @  0x806b970  (unknown)

      Start 19: detect_structure_test
19/67 Test #19: detect_structure_test .......................   Passed    0.00 sec

...

99% tests passed, 1 tests failed out of 67

Total Test time (real) = 113.06 sec

The following tests FAILED:
	 18 - cubic_interpolation_test (OTHER_FAULT)
Errors while running CTest
make[1]: *** [test] Error 8
```

On the following configurations the compilation and tests ran fine
- ubuntu 14.04 amd64
- ubuntu 16.04 i386
- ubuntu 16.04 amd64

**Comment by sandwichmaker** [comment] 2016-08-31 14:53
sorry for taking so long to look at this.
I am looking at this now actively.  do you have instructions on how to do a 32bit build and replicate this?

**Comment by NeroBurner** [comment] 2016-09-02 14:16
I'm working with schroots, but I think a 32bit docker container would also be enough

but with debootstrap and shroot on an Ubuntu system (14.04 or 16.04) it should be like the following

install debootstrap and schroot
```
sudo apt-get install debootstrap schroot
```

create a directory for the schroots to reside in (in my example all schroots are in `/mnt/chroots`)
```
sudo mkdir /mnt/chroots
```

bootstrap a ubuntu 14.04 i386 system
```
sudo debootstrap --variant=buildd --arch=i386 trusty /mnt/chroots/Ubuntu_trusty_i386_test "http://archive.ubuntu.com/ubuntu/"
```

create a schroot config file `/etc/schroot/chroot.d/Ubuntu_trusty_i386_test.conf`. Replace `$USER` with your own user
```
[Ubuntu_trusty_i386_test]
description=Ubuntu trusty for i386 with overlayfs
type=directory
directory=/mnt/chroots/Ubuntu_trusty_i386_test
union-type=overlayfs
users=$USER
root-users=$USER
source-users=$USER
source-root-users=$USER
```

Install the dependencies into the schroot (permanently thanks to the source: keyword). Execute as your own user
```
schroot -c source:Ubuntu_trusty_i386_test -u root -- apt-get install -qy software-properties-common
schroot -c source:Ubuntu_trusty_i386_test -u root -- add-apt-repository universe
schroot -c source:Ubuntu_trusty_i386_test -u root -- apt-get update
schroot -c source:Ubuntu_trusty_i386_test -u root -- apt-get install -qy git lsb-release gdb cmake libgoogle-glog-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev
```

Now your schroot is ready to be used as build environment

Download ceres-solver-1.11.0. Extract it and change into the build folder and change into the schroot environment
```
cd ceres-solver-1.11.0
schroot -c Ubuntu_trusty_i386_test
```

In the schroot environment start an out-of-source-build

```
mkdir build
cd build
cmake ..
make -j4
make test
```

**Comment by sandwichmaker** [comment] 2016-09-03 02:56
Thank you, I will try this out.
I know what the issue is, its a numerical cancellation problem, I want to figure out what is happening before figuring out how to solve it.

**Comment by sandwichmaker** [comment] 2016-09-04 14:44
from @debalance 

cubic_interpolation_test is failing on Debian's i386 and kfreebsd-i386 ports,
build logs are available here:
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=i386&ver=1.11.0%2Bgit20160903-1&stamp=1472996344
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=kfreebsd-i386&ver=1.11.0%2Bgit20160903-1&stamp=1472996844

**Comment by sandwichmaker** [comment] 2016-09-06 16:01
@debalance could you try the build at head? it should fix this issue. Still looking at the gradient checker issue.

**Comment by debalance** [comment] 2016-09-07 21:51
Yes, I'll make a package from current head and upload it to Debian's experimental suite, that way we get results for all architectures.

**Comment by debalance** [comment] 2016-09-07 22:51
Results and logs will be available here soon:
https://buildd.debian.org/status/package.php?p=ceres-solver&suite=experimental

**Comment by debalance** [comment] 2016-09-08 06:04
Now cubic_interpolation_test passes on (kfreebsd-)i386 as can be seen here:
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=i386&ver=1.11.0%2Bgit20160906-1&stamp=1473291891
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=kfreebsd-i386&ver=1.11.0%2Bgit20160906-1&stamp=1473291828

**Comment by sandwichmaker** [comment] 2016-09-08 10:52
Thanks for checkping @debalance code is already upstream, so closing this bug.

**Closed by sandwichmaker** 2016-09-08 10:52 UTC
Labels: bug
