### ISSUE TITLE
CUDA support not enabled when Ceres was built

### ISSUE THREAD

**Issue by Joeljensen28** [ceres-solver/ceres-solver#1107] opened 2024-09-30 21:26 UTC
Hi all, I am working with the COLMAP SfM library trying to build dense reconstructions which uses the ceres solver library. I am getting this issue which seems to be related to how my ceres solver library was compiled.
```
W20240930 17:48:28.491569 25592 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
```
After this error appears several dozen times, it finally throws this:
```
E20240930 17:48:32.194454 25592 bundle_adjustment.cc:403] Check failed: solver_options.IsValid(&solver_error) 
Can't use DENSE_SCHUR with dense_linear_algebra_library_type = CUDA because support not enabled when Ceres was built.
```
And then aborts the process.

I am using a VM with an NVIDIA H100 GPU that I know has CUDA installed.

For detailed steps, here is what I am doing:
1. Create a brand new VM droplet
2. Install NVIDIA drivers with `sudo apt install nvidia-driver-515`
3. Install COLMAP dependencies with the following commands:
```
sudo apt-get install \
    git \
    cmake \
    ninja-build \
    build-essential \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-system-dev \
    libeigen3-dev \
    libflann-dev \
    libfreeimage-dev \
    libmetis-dev \
    libgoogle-glog-dev \
    libgtest-dev \
    libgmock-dev \
    libsqlite3-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev \
    libceres-dev

    sudo apt-get install -y \
    nvidia-cuda-toolkit \
    nvidia-cuda-toolkit-gcc
```
4. Compile COLMAP from source with the following commands:
```
git clone https://github.com/colmap/colmap.git
    cd colmap
    mkdir build
    cd build
    cmake .. -GNinja
    ninja
    sudo ninja install
```
5. Once it compiles without issue, I created a `workspace` directory, moved my image files into it using FileZilla, then ran `automatic_reconstruction` with all needed parameters. The process ran for maybe 5-10 mins before throwing the aforementioned errors at me and aborting the process.

<img width="1000" alt="Screenshot 2024-09-30 at 1 16 21 PM" src="https://github.com/user-attachments/assets/5d9acfe1-15ee-4500-94dd-d987896704b8">

 - OS: Ubuntu 24.04

How do I "compile ceres with CUDA support"?

Thanks in advance!

Note: I have also made a [ticket](https://github.com/colmap/colmap/issues/2817) in COLMAPs repo, but the issue seems to be more closely related to ceres, so I opened one here as well.

**Comment by sandwichmaker** [comment] 2024-09-30 21:40
This is a bit weird, because you are getting two classes of errors.

```
W20240930 17:48:28.491569 25592 levenberg_marquardt_strategy.cc:123] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
```

which clearly says that Eigen was being used for Cholesky factorization and it failed. This has nothing to do with CUDA. I suspect this is a call to Ceres which is not the large bundle adjustment call. This is perhaps a resectioning or triangulation call? where DENSE_NORMAL_CHOLESKY is your linear solver.

This is not a fatal error, it has to do with the fact that sometimes the Gauss-Newton system is too poorly conditioned for Cholesky factorization to succed, Ceres will increase the regularization and retry. 

The second error 
```
E20240930 17:48:32.194454 25592 bundle_adjustment.cc:403] Check failed: solver_options.IsValid(&solver_error) 
Can't use DENSE_SCHUR with dense_linear_algebra_library_type = CUDA because support not enabled when Ceres was built.
```

is CUDA related, but it has to do with how colmap builds and uses Ceres Solver. Perhaps you do not have CUDA + CUDSS installed on your system but colmap thinks it is?

**Comment by Joeljensen28** [comment] 2024-09-30 21:59
I know for certain I at least have CUDA installed as when I run `nvcc --version` it tells me it's version 12. Although, I don't have CUDSS installed. I will look into that and see if it resolves the issue.

**Comment by sandwichmaker** [comment] 2024-09-30 23:07
do you know what linear solver is being used? if its DENSE_SCHUR, then you only need CUDA, if you are using SPARSE_SCHUR then you are going to need CUDA and CUDSS.

**Comment by sandwichmaker** [comment] 2024-09-30 23:08
also what version of ceres solver are you using? unless you are using the version at head CUDSS is not available/an issue.

**Comment by ahojnnes** [comment] 2024-10-04 06:56
I believe this is caused by a bug in colmap that is hopefully fixed with this PR: https://github.com/colmap/colmap/pull/2822

**Comment by sandwichmaker** [comment] 2024-10-04 13:25
Thanks @ahojnnes !

**Closed** 2024-10-04 13:26 UTC
Labels: question, NVIDIA CUDA
