### ISSUE TITLE
Ceres auto diff does not support Eigen::SelfAdjointEigenSolver

### ISSUE THREAD

**Issue by nemeshnorbert** [ceres-solver/ceres-solver#912] opened 2022-11-11 11:13 UTC
While trying to use autodiff feature for the function that regularizes eigenvalues of the symmentric positive definite matrix I've encountered a few compilation errors.
Here is the code I tried to compile
```cpp
template <typename ScalarT>
class PlaneCovarianceRegularizer : public ICovarianceRegularizer<ScalarT> {
public:
    Eigen::Matrix3<ScalarT> operator()(const Eigen::Matrix3<ScalarT>& covariance) const override {
        const auto solver = Eigen::SelfAdjointEigenSolver<Eigen::Matrix3<ScalarT>>{covariance};
        return solver.eigenvectors() *
               Eigen::DiagonalMatrix<ScalarT, 3>(ScalarT(1.0), ScalarT(1.0), this->epsilon_) *
               solver.eigenvectors().transpose();
    }

    void setEpsilon(ScalarT epsilon) {
        assert(epsilon > ScalarT(0.0));
        this->epsilon_ = epsilon;
    }

    ScalarT getEpsilon() const { return this->epsilon_; }

private:
    ScalarT epsilon_ = ScalarT(1e-3);
};
```
Here are the compilation errors
```console
In file included from /usr/include/eigen3/Eigen/Core:257,
                 from /usr/include/eigen3/Eigen/Geometry:11,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/thread_safe_map_registration.hpp:3,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:1:
/usr/include/eigen3/Eigen/src/Core/functors/AssignmentFunctors.h: In instantiation of ‘void Eigen::internal::assign_op<DstScalar, SrcScalar>::assignCoeff(DstScalar&, const SrcScalar&) const [with DstScalar = ceres::Jet<double, 7>; SrcScalar = double]’:
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:660:5:   required from ‘void Eigen::internal::generic_dense_assignment_kernel<DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version>::assignCoeff(Eigen::Index) [with DstEvaluatorTypeT = Eigen::internal::evaluator<Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1> >; SrcEvaluatorTypeT = Eigen::internal::evaluator<Eigen::Matrix<double, 3, 1> >; Functor = Eigen::internal::assign_op<ceres::Jet<double, 7>, double>; int Version = 0; Eigen::Index = long int]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:247:5:   required from ‘static void Eigen::internal::copy_using_evaluator_LinearTraversal_CompleteUnrolling<Kernel, Index, Stop>::run(Kernel&) [with Kernel = Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1> >, Eigen::internal::evaluator<Eigen::Matrix<double, 3, 1> >, Eigen::internal::assign_op<ceres::Jet<double, 7>, double>, 0>; int Index = 0; int Stop = 3]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:528:106:   required from ‘static void Eigen::internal::dense_assignment_loop<Kernel, 1, 2>::run(Kernel&) [with Kernel = Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1> >, Eigen::internal::evaluator<Eigen::Matrix<double, 3, 1> >, Eigen::internal::assign_op<ceres::Jet<double, 7>, double>, 0>]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:785:37:   required from ‘void Eigen::internal::call_dense_assignment_loop(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1>; SrcXprType = Eigen::Matrix<double, 3, 1>; Functor = Eigen::internal::assign_op<ceres::Jet<double, 7>, double>]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:954:31:   required from ‘static void Eigen::internal::Assignment<DstXprType, SrcXprType, Functor, Eigen::internal::Dense2Dense, Weak>::run(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1>; SrcXprType = Eigen::Matrix<double, 3, 1>; Functor = Eigen::internal::assign_op<ceres::Jet<double, 7>, double>; Weak = void]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:890:49:   [ skipping 3 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/eigen3/Eigen/src/Core/Matrix.h:423:29:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, 3, 1>; _Scalar = ceres::Jet<double, 7>; int _Rows = 3; int _Cols = 1; int _Options = 0; int _MaxRows = 3; int _MaxCols = 1]’
/usr/include/eigen3/Eigen/src/Geometry/RotationBase.h:128:32:   required from ‘static Eigen::internal::rotation_base_generic_product_selector<RotationDerived, OtherVectorType, true>::ReturnType Eigen::internal::rotation_base_generic_product_selector<RotationDerived, OtherVectorType, true>::run(const RotationDerived&, const OtherVectorType&) [with RotationDerived = Eigen::Quaternion<ceres::Jet<double, 7>, 0>; OtherVectorType = Eigen::Matrix<double, 3, 1>; Eigen::internal::rotation_base_generic_product_selector<RotationDerived, OtherVectorType, true>::ReturnType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1>; typename RotationDerived::Scalar = ceres::Jet<double, 7>]’
/usr/include/eigen3/Eigen/src/Geometry/RotationBase.h:72:89:   required from ‘typename Eigen::internal::rotation_base_generic_product_selector<Derived, OtherDerived, OtherDerived::IsVectorAtCompileTime>::ReturnType Eigen::RotationBase<Derived, _Dim>::operator*(const Eigen::EigenBase<OtherDerived>&) const [with OtherDerived = Eigen::Matrix<double, 3, 1>; Derived = Eigen::Quaternion<ceres::Jet<double, 7>, 0>; int _Dim = 3; typename Eigen::internal::rotation_base_generic_product_selector<Derived, OtherDerived, OtherDerived::IsVectorAtCompileTime>::ReturnType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1>]’
/rep/ros2/src/localization/localization_pct/include/localization_pct/registration/impl/sat_litamin_impl.hpp:182:62:   required from ‘bool sat::localization::pct::registration::detail::Litamin<PointSourceT, PointTargetT, ScalarT>::LitaminCostFunctor::operator()(const T*, T*) const [with T = ceres::Jet<double, 7>; PointSourceT = pcl::PointXYZI; PointTargetT = pcl::PointXYZI; ScalarT = float]’
/usr/include/ceres/autodiff_first_order_function.h:132:21:   required from ‘bool ceres::AutoDiffFirstOrderFunction<FirstOrderFunctor, kNumParameters>::Evaluate(const double*, double*, double*) const [with FirstOrderFunctor = sat::localization::pct::registration::detail::Litamin<pcl::PointXYZI, pcl::PointXYZI, float>::LitaminCostFunctor; int kNumParameters = 7]’
/usr/include/ceres/autodiff_first_order_function.h:113:8:   required from here
/usr/include/eigen3/Eigen/src/Core/functors/AssignmentFunctors.h:24:102: error: no match for ‘operator=’ (operand types are ‘ceres::Jet<double, 7>’ and ‘const double’)
   24 |   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff(DstScalar& a, const SrcScalar& b) const { a = b; }
      |                                                                                                    ~~^~~
In file included from /usr/include/ceres/internal/autodiff.h:152,
                 from /usr/include/ceres/autodiff_cost_function.h:130,
                 from /usr/include/ceres/ceres.h:37,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/impl/sat_litamin_impl.hpp:5,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/sat_litamin.hpp:4,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/factory.hpp:14,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:3:
/usr/include/ceres/jet.h:211:8: note: candidate: ‘ceres::Jet<double, 7>& ceres::Jet<double, 7>::operator=(const ceres::Jet<double, 7>&)’
  211 | struct Jet {
      |        ^~~
/usr/include/ceres/jet.h:211:8: note:   no known conversion for argument 1 from ‘const double’ to ‘const ceres::Jet<double, 7>&’
/usr/include/ceres/jet.h:211:8: note: candidate: ‘ceres::Jet<double, 7>& ceres::Jet<double, 7>::operator=(ceres::Jet<double, 7>&&)’
/usr/include/ceres/jet.h:211:8: note:   no known conversion for argument 1 from ‘const double’ to ‘ceres::Jet<double, 7>&&’
In file included from /usr/include/eigen3/Eigen/Eigenvalues:36,
                 from /usr/include/eigen3/Eigen/Dense:7,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/map.hpp:3,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/thread_safe_map_registration.hpp:9,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:1:
/usr/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h: In instantiation of ‘static void Eigen::internal::tridiagonalization_inplace_selector<MatrixType, 3, false>::run(MatrixType&, DiagonalType&, SubDiagonalType&, CoeffVectorType&, bool) [with DiagonalType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1>; SubDiagonalType = Eigen::Matrix<ceres::Jet<double, 7>, 2, 1, 0, 2, 1>; CoeffVectorType = Eigen::Matrix<ceres::Jet<double, 7>, 2, 1, 0, 2, 1>; MatrixType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>]’:
/usr/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:434:55:   required from ‘void Eigen::internal::tridiagonalization_inplace(MatrixType&, DiagonalType&, SubDiagonalType&, CoeffVectorType&, bool) [with MatrixType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>; DiagonalType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1>; SubDiagonalType = Eigen::Matrix<ceres::Jet<double, 7>, 2, 1, 0, 2, 1>; CoeffVectorType = Eigen::Matrix<ceres::Jet<double, 7>, 2, 1, 0, 2, 1>]’
/usr/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:458:39:   required from ‘Eigen::SelfAdjointEigenSolver<MatrixType>& Eigen::SelfAdjointEigenSolver<_MatrixType>::compute(const Eigen::EigenBase<OtherDerived>&, int) [with InputType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>; _MatrixType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>]’
/usr/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:181:7:   required from ‘Eigen::SelfAdjointEigenSolver<_MatrixType>::SelfAdjointEigenSolver(const Eigen::EigenBase<OtherDerived>&, int) [with InputType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>; _MatrixType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>]’
/rep/ros2/src/localization/localization_pct/include/localization_pct/registration/impl/regularization.hpp:92:20:   required from ‘Eigen::Matrix3<ScalarT> sat::localization::pct::registration::detail::NormalizedMinimalEigenvalueCovarianceRegularizer<ScalarT>::operator()(Eigen::Matrix3<ScalarT>&) const [with ScalarT = ceres::Jet<double, 7>; Eigen::Matrix3<ScalarT> = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>]’
/rep/ros2/src/localization/localization_pct/include/localization_pct/registration/impl/regularization.hpp:91:29:   required from here
/usr/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:498:13: error: no match for ‘operator<<’ (operand types are ‘Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>’ and ‘int’)
  498 |         mat << 1,   0,    0,
      |         ~~~~^~~~
In file included from /usr/include/eigen3/Eigen/Core:321,
                 from /usr/include/eigen3/Eigen/Geometry:11,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/thread_safe_map_registration.hpp:3,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:1:
/usr/include/eigen3/Eigen/src/Core/CommaInitializer.h:148:52: note: candidate: ‘Eigen::CommaInitializer<Derived> Eigen::DenseBase<Derived>::operator<<(const Scalar&) [with Derived = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>; Eigen::DenseBase<Derived>::Scalar = ceres::Jet<double, 7>]’
  148 | EIGEN_DEVICE_FUNC inline CommaInitializer<Derived> DenseBase<Derived>::operator<< (const Scalar& s)
      |                                                    ^~~~~~~~~~~~~~~~~~
/usr/include/eigen3/Eigen/src/Core/CommaInitializer.h:148:98: note:   no known conversion for argument 1 from ‘int’ to ‘const Scalar&’ {aka ‘const ceres::Jet<double, 7>&’}
  148 | EIGEN_DEVICE_FUNC inline CommaInitializer<Derived> DenseBase<Derived>::operator<< (const Scalar& s)
      |                                                                                    ~~~~~~~~~~~~~~^
/usr/include/eigen3/Eigen/src/Core/CommaInitializer.h:157:1: note: candidate: ‘template<class OtherDerived> Eigen::CommaInitializer<Derived> Eigen::DenseBase<Derived>::operator<<(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = OtherDerived; Derived = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>]’
  157 | DenseBase<Derived>::operator<<(const DenseBase<OtherDerived>& other)
      | ^~~~~~~~~~~~~~~~~~
/usr/include/eigen3/Eigen/src/Core/CommaInitializer.h:157:1: note:   template argument deduction/substitution failed:
In file included from /usr/include/eigen3/Eigen/Eigenvalues:36,
                 from /usr/include/eigen3/Eigen/Dense:7,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/map.hpp:3,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/thread_safe_map_registration.hpp:9,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:1:
/usr/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:498:13: note:   mismatched types ‘const Eigen::DenseBase<Derived>’ and ‘int’
  498 |         mat << 1,   0,    0,
      |         ~~~~^~~~
In file included from /usr/include/eigen3/Eigen/Core:269,
                 from /usr/include/eigen3/Eigen/Geometry:11,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/thread_safe_map_registration.hpp:3,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:1:
/usr/include/eigen3/Eigen/src/Core/IO.h:249:16: note: candidate: ‘template<class Derived> std::ostream& Eigen::operator<<(std::ostream&, const Eigen::DenseBase<Derived>&)’
  249 | std::ostream & operator <<
      |                ^~~~~~~~
/usr/include/eigen3/Eigen/src/Core/IO.h:249:16: note:   template argument deduction/substitution failed:
In file included from /usr/include/eigen3/Eigen/Eigenvalues:36,
                 from /usr/include/eigen3/Eigen/Dense:7,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/map.hpp:3,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/thread_safe_map_registration.hpp:9,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:1:
/usr/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:498:13: note:   mismatched types ‘const Eigen::DenseBase<Derived>’ and ‘int’
  498 |         mat << 1,   0,    0,
      |         ~~~~^~~~
In file included from /usr/include/ceres/internal/autodiff.h:152,
                 from /usr/include/ceres/autodiff_cost_function.h:130,
                 from /usr/include/ceres/ceres.h:37,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/impl/sat_litamin_impl.hpp:5,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/sat_litamin.hpp:4,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/factory.hpp:14,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:3:
/usr/include/ceres/jet.h:1239:22: note: candidate: ‘template<class T, int N> std::ostream& ceres::operator<<(std::ostream&, const ceres::Jet<T, N>&)’
 1239 | inline std::ostream& operator<<(std::ostream& s, const Jet<T, N>& z) {
      |                      ^~~~~~~~
/usr/include/ceres/jet.h:1239:22: note:   template argument deduction/substitution failed:
In file included from /usr/include/eigen3/Eigen/Eigenvalues:36,
                 from /usr/include/eigen3/Eigen/Dense:7,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/map.hpp:3,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/thread_safe_map_registration.hpp:9,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:1:
/usr/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:498:13: note:   mismatched types ‘const ceres::Jet<T, N>’ and ‘int’
  498 |         mat << 1,   0,    0,
      |         ~~~~^~~~
In file included from /usr/include/eigen3/Eigen/Core:173,
                 from /usr/include/eigen3/Eigen/Geometry:11,
                 from /rep/ros2/src/localization/localization_pct/include/localization_pct/registration/thread_safe_map_registration.hpp:3,
                 from /rep/ros2/src/localization/localization_pct/src/registration/thread_safe_map_registration.cpp:1:
/usr/include/eigen3/Eigen/src/Core/MathFunctionsImpl.h: In instantiation of ‘RealScalar Eigen::internal::positive_real_hypot(const RealScalar&, const RealScalar&) [with RealScalar = ceres::Jet<double, 7>]’:
/usr/include/eigen3/Eigen/src/Core/MathFunctionsImpl.h:104:43:   required from ‘static Eigen::internal::hypot_impl<Scalar>::RealScalar Eigen::internal::hypot_impl<Scalar>::run(const Scalar&, const Scalar&) [with Scalar = ceres::Jet<double, 7>; Eigen::internal::hypot_impl<Scalar>::RealScalar = ceres::Jet<double, 7>]’
/usr/include/eigen3/Eigen/src/Core/MathFunctions.h:1333:49:   required from ‘typename Eigen::internal::hypot_retval<typename Eigen::internal::global_math_functions_filtering_base<Scalar>::type>::type Eigen::numext::hypot(const Scalar&, const Scalar&) [with Scalar = ceres::Jet<double, 7>; typename Eigen::internal::hypot_retval<typename Eigen::internal::global_math_functions_filtering_base<Scalar>::type>::type = ceres::Jet<double, 7>]’
/usr/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:854:39:   required from ‘void Eigen::internal::tridiagonal_qr_step(RealScalar*, RealScalar*, Index, Index, Scalar*, Index) [with int StorageOrder = 0; RealScalar = ceres::Jet<double, 7>; Scalar = ceres::Jet<double, 7>; Index = long int]’
/usr/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:548:87:   required from ‘Eigen::ComputationInfo Eigen::internal::computeFromTridiagonal_impl(DiagType&, SubDiagType&, Eigen::Index, bool, MatrixType&) [with MatrixType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>; DiagType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 1, 0, 3, 1>; SubDiagType = Eigen::Matrix<ceres::Jet<double, 7>, 2, 1, 0, 2, 1>; Eigen::Index = long int]’
/usr/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:460:49:   required from ‘Eigen::SelfAdjointEigenSolver<MatrixType>& Eigen::SelfAdjointEigenSolver<_MatrixType>::compute(const Eigen::EigenBase<OtherDerived>&, int) [with InputType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>; _MatrixType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>]’
/usr/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:181:7:   required from ‘Eigen::SelfAdjointEigenSolver<_MatrixType>::SelfAdjointEigenSolver(const Eigen::EigenBase<OtherDerived>&, int) [with InputType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>; _MatrixType = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>]’
/rep/ros2/src/localization/localization_pct/include/localization_pct/registration/impl/regularization.hpp:92:20:   required from ‘Eigen::Matrix3<ScalarT> sat::localization::pct::registration::detail::NormalizedMinimalEigenvalueCovarianceRegularizer<ScalarT>::operator()(Eigen::Matrix3<ScalarT>&) const [with ScalarT = ceres::Jet<double, 7>; Eigen::Matrix3<ScalarT> = Eigen::Matrix<ceres::Jet<double, 7>, 3, 3, 0, 3, 3>]’
/rep/ros2/src/localization/localization_pct/include/localization_pct/registration/impl/regularization.hpp:91:29:   required from here
/usr/include/eigen3/Eigen/src/Core/MathFunctionsImpl.h:84:43: error: ‘infinity’ is not a member of ‘Eigen::NumTraits<ceres::Jet<double, 7> >’
   84 |     return NumTraits<RealScalar>::infinity();
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/eigen3/Eigen/src/Core/MathFunctionsImpl.h:86:44: error: ‘quiet_NaN’ is not a member of ‘Eigen::NumTraits<ceres::Jet<double, 7> >’
   86 |     return NumTraits<RealScalar>::quiet_NaN();
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
make[2]: *** [CMakeFiles/localization_pct.dir/build.make:76: CMakeFiles/localization_pct.dir/src/registration/thread_safe_map_registration.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:161: CMakeFiles/localization_pct.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< localization_pct [37.9s, exited with code 2]

Summary: 35 packages finished [1min 3s]
  1 package failed: localization_pct
  1 package had stderr output: localization_pct
  1 package not processed
Error while building on host: Command '['colcon', 'build', '--packages-up-to', 'localization_eval']' returned non-zero exit status 2.

BUILD FAILED. See build logs

real    1m3.985s
user    1m0.801s
sys     5m35.884s
```
As I understand there are two major problems here

1. One cannot assign `double`/`float`/`int`/... values to `Jet<>` types
2. The `Jet<...>` type does not support `NaN` and `infinity` values.

My questions: 

1. Are these problems on the Eigen side or on the ceres side? 
2. Is there any chance that `Eiegen::SelfAdjointSolver` (and other solvers) will be supported by ceres' auto diff feature?

**Comment by sergiud** [comment] 2022-11-11 11:36
The first issue is caused by intentional prohibition of implicit conversions from a scalar to a `Jet`. This design choice however needs to be reevaluated given we previously already relaxed the semantics for comparison operators. The two missing members were probably overlooked and can be easily added.

**Comment by sergiud** [comment] 2022-11-13 16:05
I'm not aware of any.

**Comment by tanjunyao7** [comment] 2022-11-14 03:50
hi bro, I suggest using analytical solution of eigenvalue decomposition following this survey:
https://hal.archives-ouvertes.fr/hal-01501221/document

**Comment by nemeshnorbert** [comment] 2022-11-14 08:15
@tanjunyao7 Thank you for the reference. I believe these formulae are already implemented in Eigen here

https://github.com/libigl/eigen/blob/1f05f51517ec4fd91eed711e0f89e97a7c028c0e/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h#L567

**Comment by nemeshnorbert** [comment] 2022-11-14 11:57
@tanjunyao7 Is it working for eigenvectors too? Tomorrow I'll  give it a try.

**Comment by sandwichmaker** [comment] 2022-11-25 22:26
I am going to close this issue, this is a general issue with iterative algorithms. You should consider differentiating the solution rather than the iterative algorithm. It will also be much faster.

**Closed by sandwichmaker** 2022-11-25 22:26 UTC
