### ISSUE TITLE
gradient_problem_solver_test failing on VS2015x64 Release

### ISSUE THREAD

**Issue by Ardavel** [ceres-solver/ceres-solver#217] opened 2016-08-22 13:33 UTC
"SolvesRosenbrockWithDefaultOptions" test from gradient_problem_solver_test.cc fails on VS2015x64 Release version. Here is the log:

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GradientProblemSolver
[ RUN      ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions
C:\Users\wszalaps\Desktop\issues\failing builds\ceres\ceres-solver-1.11.0\ceres-solver-1.11.0\internal\ceres\gradient_problem_solver_test.cc(71): erro
r: The difference between 1.0 and parameters[0] is 2.2000000000000002, which exceeds expected_tolerance, where
1.0 evaluates to 1,
parameters[0] evaluates to -1.2, and
expected_tolerance evaluates to 1.0000000000000001e-09.
C:\Users\wszalaps\Desktop\issues\failing builds\ceres\ceres-solver-1.11.0\ceres-solver-1.11.0\internal\ceres\gradient_problem_solver_test.cc(72): erro
r: The difference between 1.0 and parameters[1] is 1, which exceeds expected_tolerance, where
1.0 evaluates to 1,
parameters[1] evaluates to 0, and
expected_tolerance evaluates to 1.0000000000000001e-09.
[  FAILED  ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions (4 ms)
[----------] 1 test from GradientProblemSolver (4 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions

 1 FAILED TEST
```

I didn't manage to reproduce the error on VS2013x64 Release and VS2015x64 Debug.

**Comment by Ardavel** [comment] 2016-08-26 11:46
The problem doesn't occur if ceres is compiled with /Od flag.

**Comment by sandwichmaker** [comment] 2016-08-31 15:00
this is weird and curious. Is it possible for you run this test with logging enabled, I'd like to see the trajectory the solver is taking?

**Comment by Ardavel** [comment] 2016-09-01 07:44
This is what I've got for ceres release 1.11.0:

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GradientProblemSolver
[ RUN      ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions
I0901 09:40:12.763376 13536 gradient_problem_solver_test.cc:64] info log
E0901 09:40:12.763376 13536 gradient_problem_solver_test.cc:65] error log
   0: f: 2.122000e+02 d: 0.00e+00 g: 6.96e+02 h: 0.00e+00 s: 0.00e+00 e:  0 it: 9.20e-06 tt: 9.56e-06
W0901 09:40:12.768376 13536 line_search.cc:604] Line search failed: Wolfe bracketing phase shrank bracket width: 4.24399e-314, to < tolerance: 1e-09, with descent_direction_max_norm: 695.6, and failed to find a point satisfying the strong Wolfe conditions or a bracketing containing such a point. Accepting point found satisfying Armijo condition only, to allow continuation.
C:\Users\wszalaps\Desktop\ceres VS2015 BA crash\src\ceres-solver-1.11.0\internal\ceres\gradient_problem_solver_test.cc(77): error: The difference between 1.0 and parameters[0] is 2.2000000000000002, which exceeds expected_tolerance, where

1.0 evaluates to 1,
parameters[0] evaluates to -1.2, and
expected_tolerance evaluates to 1.0000000000000001e-09.
C:\Users\wszalaps\Desktop\ceres VS2015 BA crash\src\ceres-solver-1.11.0\internal\ceres\gradient_problem_solver_test.cc(78): error: The difference between 1.0 and parameters[1] is 1, which exceeds expected_tolerance, where
1.0 evaluates to 1,
parameters[1] evaluates to 1.2222696485912316e-311, and
expected_tolerance evaluates to 1.0000000000000001e-09.
[  FAILED  ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions (7 ms)
[----------] 1 test from GradientProblemSolver (7 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (10 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions

 1 FAILED TEST
```

This one is for current master (commit 716f049a7b91a8f3a4632c367d9534d1d9190a81):

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GradientProblemSolver
[ RUN      ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions
   0: f: 2.122000e+02 d: 0.00e+00 g: 6.96e+02 h: 0.00e+00 s: 0.00e+00 e:  0 it: 1.27e-05 tt: 1.27e-05
W0901 09:42:50.108376  4848 line_search.cc:604] Line search failed: Wolfe bracketing phase shrank bracket width: 5.11798e-307, to < tolerance: 1e-09, with descent_direction_max_norm: 695.6, and failed to find a point satisfying the strong Wolfe conditions or a bracketing containing such a point. Accepting point found satisfying Armijo condition only, to allow continuation.
C:\Users\wszalaps\Desktop\ceres VS2015 BA crash\src\ceres-solver-master\internal\ceres\gradient_problem_solver_test.cc(72): error: The difference between 1.0 and parameters[0] is 2.2000000000000002, which exceeds expected_tolerance, where

1.0 evaluates to 1,
parameters[0] evaluates to -1.2, and
expected_tolerance evaluates to 1.0000000000000001e-09.
C:\Users\wszalaps\Desktop\ceres VS2015 BA crash\src\ceres-solver-master\internal\ceres\gradient_problem_solver_test.cc(73): error: The difference between 1.0 and parameters[1] is 1, which exceeds expected_tolerance, where
1.0 evaluates to 1,
parameters[1] evaluates to 1.4739788837813256e-304, and
expected_tolerance evaluates to 1.0000000000000001e-09.
[  FAILED  ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions (7 ms)
[----------] 1 test from GradientProblemSolver (7 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (9 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions

 1 FAILED TEST
```

**Comment by sandwichmaker** [comment] 2016-09-01 14:28
@alexsmac this looks like the line search solver is not making any progress at all.

**Comment by alexsmac** [comment] 2016-09-01 19:30
Interesting, I see this:

```
~/code/external/ceres-solver/build > ./bin/gradient_problem_solver_test -logtostderr -vmodule=line_search:3                                            Thu  1 Sep 20:15
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GradientProblemSolver
[ RUN      ] GradientProblemSolver.SolvesRosenbrockWithDefaultOptions
I0901 20:15:27.049526 1983718144 callbacks.cc:105]    0: f: 2.122000e+02 d: 0.00e+00 g: 6.96e+02 h: 0.00e+00 s: 0.00e+00 e:  0 it: 1.22e-05 tt: 1.22e-05
I0901 20:15:27.050164 1983718144 line_search.cc:574] Bracketing phase found step size: 1.43760782e-03, satisfying strong Wolfe conditions, initial_position: [x: 0.00000000e+00, value: 2.12200000e+02, gradient: -5.66803360e+05, value_is_valid: 1, gradient_is_valid: 1], current: [x: 1.43760782e-03, value: 1.54299228e+01, gradient: 4.06888286e+04, value_is_valid: 1, gradient_is_valid: 1]
```

which looks healthy.  As this worked in previous versions of MSVC, and as it works when you compile with /Od, which should disable all optimisations, this feels like it could be an MSVC optimisation bug.  Have you tried experimenting with other /O options?  It would be interesting to know which optimisation is actually triggering this.

**Comment by Ardavel** [comment] 2016-09-02 06:50
I was manipulating optimization flags for "ceres" project. I left /O2 intact and changed /Ob settings (inline function expansion). It turned out that changing from /Ob2 (any suitable) to /Ob0 (disabled) made the test passing. With /Ob1 (only __inline) it was still failing. I can add I'm testing it with ceres 1.11.0 release and for VS2015x64 Update 3.

**Comment by sandwichmaker** [comment] 2016-09-02 07:55
what version of eigen are you using?

**Comment by Ardavel** [comment] 2016-09-02 08:03
Eigen 3.2.7.

**Comment by alexsmac** [comment] 2016-09-02 08:26
What is the output from the rosenbrock example?

**Comment by Ardavel** [comment] 2016-09-02 08:49
With /Ob2:

`   0: f: 2.420000e+01 d: 0.00e+00 g: 2.16e+02 h: 0.00e+00 s: 0.00e+00 e:  0 it: 7.08e-06 tt: 7.08e-06
W0902 10:43:52.171300  8040 line_search.cc:604] Line search failed: Wolfe bracketing phase shrank bracket width: 5.26427e-90, to < tolerance: 1e-09, with descent_direction_max_norm: 215.6, and failed to find a point satisfying the strong Wolfe conditions or a bracketing containing such a point. Accepting point found satisfying Armijo condition only, to allow continuation.

Solver Summary (v 1.11.0-eigen-(3.2.7)-no_lapack-openmp-no_custom_blas)

Parameters                                  2
Line search direction              LBFGS (20)
Line search type                  CUBIC WOLFE


Cost:
Initial                          2.420000e+01
Final                            2.420000e+01
Change                           0.000000e+00

Minimizer iterations                        1

Time (in seconds):

  Cost evaluation                      0.0000
  Gradient evaluation                  0.0000
  Polynomial minimization              0.0000
Total                                  0.0086

Termination:                      CONVERGENCE (Parameter tolerance reached. Relative step_norm: 7.847881e-88 <= 1.000000e-08.)

Initial x: -1.2 y: 1
Final   x: -1.2 y: 1`

With /Ob0:

`   0: f: 2.420000e+01 d: 0.00e+00 g: 2.16e+02 h: 0.00e+00 s: 0.00e+00 e:  0 it: 3.11e-05 tt: 3.11e-05
   1: f: 4.280493e+00 d: 1.99e+01 g: 1.52e+01 h: 2.01e-01 s: 8.62e-04 e:  2 it: 1.32e-04 tt: 4.62e-03
   2: f: 3.571154e+00 d: 7.09e-01 g: 1.35e+01 h: 3.78e-01 s: 1.34e-01 e:  3 it: 7.50e-05 tt: 9.35e-03
   3: f: 3.440869e+00 d: 1.30e-01 g: 1.73e+01 h: 1.36e-01 s: 1.00e+00 e:  1 it: 2.26e-05 tt: 1.43e-02
   4: f: 3.213597e+00 d: 2.27e-01 g: 1.55e+01 h: 1.06e-01 s: 4.59e-01 e:  1 it: 2.51e-05 tt: 1.96e-02
   5: f: 2.839723e+00 d: 3.74e-01 g: 1.05e+01 h: 1.34e-01 s: 5.24e-01 e:  1 it: 7.61e-05 tt: 2.49e-02
   6: f: 2.448490e+00 d: 3.91e-01 g: 1.29e+01 h: 3.04e-01 s: 1.00e+00 e:  1 it: 2.37e-05 tt: 2.92e-02
   7: f: 1.943019e+00 d: 5.05e-01 g: 4.00e+00 h: 8.81e-02 s: 7.43e-01 e:  1 it: 5.70e-05 tt: 3.43e-02
   8: f: 1.731469e+00 d: 2.12e-01 g: 7.36e+00 h: 1.71e-01 s: 4.60e-01 e:  2 it: 6.48e-05 tt: 3.99e-02
   9: f: 1.503267e+00 d: 2.28e-01 g: 6.47e+00 h: 8.66e-02 s: 1.00e+00 e:  1 it: 5.20e-05 tt: 4.51e-02
  10: f: 1.228331e+00 d: 2.75e-01 g: 2.00e+00 h: 7.70e-02 s: 7.90e-01 e:  1 it: 3.33e-05 tt: 4.95e-02
  11: f: 1.016523e+00 d: 2.12e-01 g: 5.15e+00 h: 1.39e-01 s: 3.76e-01 e:  2 it: 1.00e-04 tt: 5.41e-02
  12: f: 9.145773e-01 d: 1.02e-01 g: 6.74e+00 h: 7.98e-02 s: 1.00e+00 e:  1 it: 4.21e-05 tt: 5.83e-02
  13: f: 7.508302e-01 d: 1.64e-01 g: 3.88e+00 h: 5.76e-02 s: 4.93e-01 e:  1 it: 3.01e-05 tt: 6.36e-02
  14: f: 5.832378e-01 d: 1.68e-01 g: 5.56e+00 h: 1.42e-01 s: 1.00e+00 e:  1 it: 8.00e-05 tt: 6.93e-02
  15: f: 3.969581e-01 d: 1.86e-01 g: 1.64e+00 h: 1.17e-01 s: 1.00e+00 e:  1 it: 8.74e-05 tt: 7.43e-02
  16: f: 3.171557e-01 d: 7.98e-02 g: 3.84e+00 h: 1.18e-01 s: 3.97e-01 e:  2 it: 5.87e-05 tt: 7.85e-02
  17: f: 2.641257e-01 d: 5.30e-02 g: 3.27e+00 h: 6.14e-02 s: 1.00e+00 e:  1 it: 5.95e-05 tt: 8.43e-02
  18: f: 1.909730e-01 d: 7.32e-02 g: 5.29e-01 h: 8.55e-02 s: 6.82e-01 e:  1 it: 4.11e-05 tt: 8.91e-02
  19: f: 1.472012e-01 d: 4.38e-02 g: 3.11e+00 h: 1.20e-01 s: 3.47e-01 e:  2 it: 6.48e-05 tt: 9.37e-02
  20: f: 1.093558e-01 d: 3.78e-02 g: 2.97e+00 h: 8.43e-02 s: 1.00e+00 e:  1 it: 5.66e-05 tt: 9.82e-02
  21: f: 6.710346e-02 d: 4.23e-02 g: 1.42e+00 h: 9.64e-02 s: 8.85e-01 e:  1 it: 3.61e-05 tt: 1.02e-01
  22: f: 3.993377e-02 d: 2.72e-02 g: 2.30e+00 h: 1.29e-01 s: 4.63e-01 e:  2 it: 7.89e-05 tt: 1.08e-01
  23: f: 2.911794e-02 d: 1.08e-02 g: 2.55e+00 h: 6.55e-02 s: 1.00e+00 e:  1 it: 3.26e-05 tt: 1.13e-01
  24: f: 1.457683e-02 d: 1.45e-02 g: 2.77e-01 h: 6.37e-02 s: 6.14e-01 e:  1 it: 4.71e-05 tt: 1.17e-01
  25: f: 8.577515e-03 d: 6.00e-03 g: 2.86e+00 h: 1.40e-01 s: 1.00e+00 e:  1 it: 6.51e-05 tt: 1.21e-01
  26: f: 3.486574e-03 d: 5.09e-03 g: 1.76e-01 h: 1.23e-02 s: 1.00e+00 e:  1 it: 4.67e-05 tt: 1.28e-01
  27: f: 1.257570e-03 d: 2.23e-03 g: 1.39e-01 h: 5.08e-02 s: 1.00e+00 e:  1 it: 5.49e-05 tt: 1.33e-01
  28: f: 2.783568e-04 d: 9.79e-04 g: 6.20e-01 h: 6.47e-02 s: 1.00e+00 e:  1 it: 4.60e-05 tt: 1.37e-01
  29: f: 2.533399e-05 d: 2.53e-04 g: 1.68e-02 h: 1.98e-03 s: 1.00e+00 e:  1 it: 4.14e-05 tt: 1.42e-01
  30: f: 7.591572e-07 d: 2.46e-05 g: 5.40e-03 h: 9.27e-03 s: 1.00e+00 e:  1 it: 5.24e-05 tt: 1.48e-01
  31: f: 1.902460e-09 d: 7.57e-07 g: 1.62e-03 h: 1.89e-03 s: 1.00e+00 e:  1 it: 4.00e-05 tt: 1.53e-01
  32: f: 1.003030e-12 d: 1.90e-09 g: 3.50e-05 h: 3.52e-05 s: 1.00e+00 e:  1 it: 4.53e-05 tt: 1.58e-01
  33: f: 4.835994e-17 d: 1.00e-12 g: 1.05e-07 h: 1.13e-06 s: 1.00e+00 e:  1 it: 4.71e-05 tt: 1.63e-01
  34: f: 1.885250e-22 d: 4.84e-17 g: 2.69e-10 h: 1.45e-08 s: 1.00e+00 e:  1 it: 4.81e-05 tt: 1.68e-01

Solver Summary (v 1.11.0-eigen-(3.2.7)-no_lapack-openmp-no_custom_blas)

Parameters                                  2
Line search direction              LBFGS (20)
Line search type                  CUBIC WOLFE


Cost:
Initial                          2.420000e+01
Final                            1.885250e-22
Change                           2.420000e+01

Minimizer iterations                       35

Time (in seconds):

  Cost evaluation                      0.0000
  Gradient evaluation                  0.0000
  Polynomial minimization              0.0003
Total                                  0.1725

Termination:                      CONVERGENCE (Parameter tolerance reached. Relative step_norm: 1.890730e-11 <= 1.000000e-08.)

Initial x: -1.2 y: 1
Final   x: 1 y: 1`

**Comment by alexsmac** [comment] 2016-09-02 08:51
OK - so that's instructive, the issue is probably happening inside Ceres, not with the test code.

**Comment by sandwichmaker** [comment] 2016-09-04 14:48
@alexsmac do you have the appropriate visual studio setup to debug this?

**Comment by alexsmac** [comment] 2016-09-04 14:51
@sandwichmaker - no sorry. I don't have access to any Windows boxes.

**Comment by alexsmac** [comment] 2016-09-04 14:53
@Ardavel - can you please try running the NIST benchmarks using the line search solver, the spell should be something like this:

```
./bin/nist -nist_data_dir ../src/data/nist/ -minimizer line_search -line_search wolfe -line_search_direction lbfgs -line_search_interpolation cubic
```

You should see that 53/54 benchmarks pass (15/16 for the Hard benchmarks).  This should at least isolate whether the issue is within GradientProblem, or the line search solver as the NIST benchmarks do not use GradientProblem.

**Comment by Ardavel** [comment] 2016-09-04 15:14
Currently I'm unable to run it but I'll provide the results tomorrow morning (in 15 hours in my timezone) + the time required for running the benchmarks.

**Comment by alexsmac** [comment] 2016-09-04 15:16
Great thanks - the benchmarks should only take 2-3 seconds to run.

**Comment by Ardavel** [comment] 2016-09-05 07:00
I attach logs for 1.11.0 release with \Ob0 and \Ob2.
[nist_Ob0.txt](https://github.com/ceres-solver/ceres-solver/files/454514/nist_Ob0.txt)
[nist_Ob2.txt](https://github.com/ceres-solver/ceres-solver/files/454513/nist_Ob2.txt)

**Comment by alexsmac** [comment] 2017-01-16 18:26
@Ardavel have you been able to replicate this with the latest version of Ceres & MSVC?

**Comment by sandwichmaker** [comment] 2018-07-01 20:34
I am going to close this. If there is new information or reproduction, please re-open.

**Closed by sandwichmaker** 2018-07-01 20:34 UTC
Labels: bug
