### ISSUE TITLE
cuda_kernels_test is failing at HEAD

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#889] opened 2022-09-22 16:57 UTC
This is with the latest cuda SDK

```
"name" : "CUDA SDK",
"version" : "11.7.20220729"
```

and `gcc-11`.

Here is the failing log.

```
(LOAS)  cmake-build: ./bin/cuda_kernels_test 
Running main() from gmock_main.cc
[==========] Running 7 tests from 6 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from CudaFP64ToFP32
[ RUN      ] CudaFP64ToFP32.SimpleConversions
[       OK ] CudaFP64ToFP32.SimpleConversions (733 ms)
[ RUN      ] CudaFP64ToFP32.NumericallyExtremeValues
[       OK ] CudaFP64ToFP32.NumericallyExtremeValues (4 ms)
[----------] 2 tests from CudaFP64ToFP32 (738 ms total)

[----------] 1 test from CudaFP32ToFP64
[ RUN      ] CudaFP32ToFP64.SimpleConversions
[       OK ] CudaFP32ToFP64.SimpleConversions (4 ms)
[----------] 1 test from CudaFP32ToFP64 (4 ms total)

[----------] 1 test from CudaSetZeroFP32
[ RUN      ] CudaSetZeroFP32.NonZeroInput
[       OK ] CudaSetZeroFP32.NonZeroInput (4 ms)
[----------] 1 test from CudaSetZeroFP32 (4 ms total)

[----------] 1 test from CudaSetZeroFP64
[ RUN      ] CudaSetZeroFP64.NonZeroInput
[       OK ] CudaSetZeroFP64.NonZeroInput (4 ms)
[----------] 1 test from CudaSetZeroFP64 (4 ms total)

[----------] 1 test from CudaDsxpy
[ RUN      ] CudaDsxpy.DoubleValues
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 1
  2.0 * fp32_cpu_a[i]
    Which is: 2
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 1.5
  2.0 * fp32_cpu_a[i]
    Which is: 3
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 2
  2.0 * fp32_cpu_a[i]
    Which is: 4
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 2.5
  2.0 * fp32_cpu_a[i]
    Which is: 5
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 3
  2.0 * fp32_cpu_a[i]
    Which is: 6
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 3.5
  2.0 * fp32_cpu_a[i]
    Which is: 7
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 4
  2.0 * fp32_cpu_a[i]
    Which is: 8
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 4.5
  2.0 * fp32_cpu_a[i]
    Which is: 9
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 5
  2.0 * fp32_cpu_a[i]
    Which is: 10
[  FAILED  ] CudaDsxpy.DoubleValues (4 ms)
[----------] 1 test from CudaDsxpy (4 ms total)

[----------] 1 test from CudaDtDxpy
[ RUN      ] CudaDtDxpy.ComputeFourItems
[       OK ] CudaDtDxpy.ComputeFourItems (4 ms)
[----------] 1 test from CudaDtDxpy (4 ms total)

[----------] Global test environment tear-down
[==========] 7 tests from 6 test suites ran. (760 ms total)
[  PASSED  ] 6 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CudaDsxpy.DoubleValues

 1 FAILED TEST
(LOAS)  cmake-build: 
```

**Comment by sandwichmaker** [comment] 2022-09-22 16:57
cc: @joydeep-b

**Comment by joydeep-b** [comment] 2022-09-22 17:00
Ack. Please assign to me.

**Comment by joydeep-b** [comment] 2022-09-22 17:12
Hmm unfortunately I am not able to reproduce this issue - I tried on three computers with a 2080Ti, an A2000, and an A6000. 
Could you run with `--v 3 --alsologtostderr` ? I'd like to see the output of the GPU props.

**Comment by sandwichmaker** [comment] 2022-09-22 17:23
I think it is some sort of timing error. Because when I add these logging flags, sometimes it passes, sometimes it fails.

Here is a passing run.

```
(LOAS)  cmake-build: ./bin/cuda_kernels_test --v=3 --alsologtostderr
Running main() from gmock_main.cc
[==========] Running 7 tests from 6 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from CudaFP64ToFP32
[ RUN      ] CudaFP64ToFP32.SimpleConversions
I20220922 10:22:00.006143 1813759 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   4012 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:00.702167 1813759 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.35780      0.35780
                cusolverDnCreate :    0.08077      0.43856
                  cusparseCreate :    0.15219      0.59075
       cudaStreamCreateWithFlags :    0.00002      0.59077
                       SetStream :    0.00001      0.59079
                           Total :    0.00000      0.59079

[       OK ] CudaFP64ToFP32.SimpleConversions (736 ms)
[ RUN      ] CudaFP64ToFP32.NumericallyExtremeValues
I20220922 10:22:00.705508 1813759 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:00.706712 1813759 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00052      0.00052
                cusolverDnCreate :    0.00050      0.00102
                  cusparseCreate :    0.00012      0.00114
       cudaStreamCreateWithFlags :    0.00001      0.00114
                       SetStream :    0.00000      0.00114
                           Total :    0.00000      0.00115

[       OK ] CudaFP64ToFP32.NumericallyExtremeValues (4 ms)
[----------] 2 tests from CudaFP64ToFP32 (740 ms total)

[----------] 1 test from CudaFP32ToFP64
[ RUN      ] CudaFP32ToFP64.SimpleConversions
I20220922 10:22:00.709909 1813759 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:00.711069 1813759 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00053      0.00053
                cusolverDnCreate :    0.00046      0.00099
                  cusparseCreate :    0.00012      0.00110
       cudaStreamCreateWithFlags :    0.00001      0.00111
                       SetStream :    0.00000      0.00111
                           Total :    0.00000      0.00111

[       OK ] CudaFP32ToFP64.SimpleConversions (4 ms)
[----------] 1 test from CudaFP32ToFP64 (4 ms total)

[----------] 1 test from CudaSetZeroFP32
[ RUN      ] CudaSetZeroFP32.NonZeroInput
I20220922 10:22:00.714277 1813759 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:00.715421 1813759 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00052      0.00052
                cusolverDnCreate :    0.00045      0.00097
                  cusparseCreate :    0.00011      0.00109
       cudaStreamCreateWithFlags :    0.00001      0.00109
                       SetStream :    0.00000      0.00110
                           Total :    0.00000      0.00110

[       OK ] CudaSetZeroFP32.NonZeroInput (4 ms)
[----------] 1 test from CudaSetZeroFP32 (4 ms total)

[----------] 1 test from CudaSetZeroFP64
[ RUN      ] CudaSetZeroFP64.NonZeroInput
I20220922 10:22:00.718654 1813759 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:00.719817 1813759 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00054      0.00054
                cusolverDnCreate :    0.00045      0.00099
                  cusparseCreate :    0.00012      0.00110
       cudaStreamCreateWithFlags :    0.00001      0.00111
                       SetStream :    0.00000      0.00111
                           Total :    0.00000      0.00111

[       OK ] CudaSetZeroFP64.NonZeroInput (4 ms)
[----------] 1 test from CudaSetZeroFP64 (4 ms total)

[----------] 1 test from CudaDsxpy
[ RUN      ] CudaDsxpy.DoubleValues
I20220922 10:22:00.723006 1813759 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:00.724273 1813759 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00055      0.00055
                cusolverDnCreate :    0.00055      0.00110
                  cusparseCreate :    0.00011      0.00121
       cudaStreamCreateWithFlags :    0.00001      0.00122
                       SetStream :    0.00000      0.00122
                           Total :    0.00000      0.00122

[       OK ] CudaDsxpy.DoubleValues (4 ms)
[----------] 1 test from CudaDsxpy (4 ms total)

[----------] 1 test from CudaDtDxpy
[ RUN      ] CudaDtDxpy.ComputeFourItems
I20220922 10:22:00.727434 1813759 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:00.728623 1813759 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00055      0.00055
                cusolverDnCreate :    0.00047      0.00102
                  cusparseCreate :    0.00011      0.00113
       cudaStreamCreateWithFlags :    0.00001      0.00114
                       SetStream :    0.00000      0.00114
                           Total :    0.00000      0.00114

[       OK ] CudaDtDxpy.ComputeFourItems (4 ms)
[----------] 1 test from CudaDtDxpy (4 ms total)

[----------] Global test environment tear-down
[==========] 7 tests from 6 test suites ran. (762 ms total)
[  PASSED  ] 7 tests.
```

Here is the failing run
```
(LOAS)  cmake-build: ./bin/cuda_kernels_test --v=3 --alsologtostderr
Running main() from gmock_main.cc
[==========] Running 7 tests from 6 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from CudaFP64ToFP32
[ RUN      ] CudaFP64ToFP32.SimpleConversions
I20220922 10:22:02.006036 1813795 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   4012 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:02.709740 1813795 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.36333      0.36333
                cusolverDnCreate :    0.08137      0.44470
                  cusparseCreate :    0.15470      0.59940
       cudaStreamCreateWithFlags :    0.00002      0.59942
                       SetStream :    0.00001      0.59944
                           Total :    0.00000      0.59944

[       OK ] CudaFP64ToFP32.SimpleConversions (742 ms)
[ RUN      ] CudaFP64ToFP32.NumericallyExtremeValues
I20220922 10:22:02.713140 1813795 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:02.714426 1813795 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00053      0.00053
                cusolverDnCreate :    0.00055      0.00108
                  cusparseCreate :    0.00012      0.00120
       cudaStreamCreateWithFlags :    0.00001      0.00120
                       SetStream :    0.00000      0.00120
                           Total :    0.00000      0.00120

[       OK ] CudaFP64ToFP32.NumericallyExtremeValues (4 ms)
[----------] 2 tests from CudaFP64ToFP32 (747 ms total)

[----------] 1 test from CudaFP32ToFP64
[ RUN      ] CudaFP32ToFP64.SimpleConversions
I20220922 10:22:02.717689 1813795 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:02.718827 1813795 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00050      0.00050
                cusolverDnCreate :    0.00046      0.00096
                  cusparseCreate :    0.00012      0.00108
       cudaStreamCreateWithFlags :    0.00001      0.00108
                       SetStream :    0.00000      0.00109
                           Total :    0.00000      0.00109

[       OK ] CudaFP32ToFP64.SimpleConversions (4 ms)
[----------] 1 test from CudaFP32ToFP64 (4 ms total)

[----------] 1 test from CudaSetZeroFP32
[ RUN      ] CudaSetZeroFP32.NonZeroInput
I20220922 10:22:02.721989 1813795 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:02.723162 1813795 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00055      0.00055
                cusolverDnCreate :    0.00045      0.00100
                  cusparseCreate :    0.00012      0.00112
       cudaStreamCreateWithFlags :    0.00001      0.00112
                       SetStream :    0.00000      0.00113
                           Total :    0.00000      0.00113

[       OK ] CudaSetZeroFP32.NonZeroInput (4 ms)
[----------] 1 test from CudaSetZeroFP32 (4 ms total)

[----------] 1 test from CudaSetZeroFP64
[ RUN      ] CudaSetZeroFP64.NonZeroInput
I20220922 10:22:02.726325 1813795 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:02.727542 1813795 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00056      0.00056
                cusolverDnCreate :    0.00049      0.00104
                  cusparseCreate :    0.00012      0.00116
       cudaStreamCreateWithFlags :    0.00001      0.00117
                       SetStream :    0.00000      0.00117
                           Total :    0.00000      0.00117

[       OK ] CudaSetZeroFP64.NonZeroInput (4 ms)
[----------] 1 test from CudaSetZeroFP64 (4 ms total)

[----------] 1 test from CudaDsxpy
[ RUN      ] CudaDsxpy.DoubleValues
I20220922 10:22:02.730712 1813795 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:02.731927 1813795 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00056      0.00056
                cusolverDnCreate :    0.00045      0.00102
                  cusparseCreate :    0.00014      0.00116
       cudaStreamCreateWithFlags :    0.00001      0.00117
                       SetStream :    0.00000      0.00117
                           Total :    0.00000      0.00117

/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 1
  2.0 * fp32_cpu_a[i]
    Which is: 2
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 1.5
  2.0 * fp32_cpu_a[i]
    Which is: 3
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 2
  2.0 * fp32_cpu_a[i]
    Which is: 4
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 2.5
  2.0 * fp32_cpu_a[i]
    Which is: 5
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 3
  2.0 * fp32_cpu_a[i]
    Which is: 6
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 3.5
  2.0 * fp32_cpu_a[i]
    Which is: 7
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 4
  2.0 * fp32_cpu_a[i]
    Which is: 8
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 4.5
  2.0 * fp32_cpu_a[i]
    Which is: 9
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:160: Failure
Expected equality of these values:
  fp64_cpu_b[i]
    Which is: 5
  2.0 * fp32_cpu_a[i]
    Which is: 10
[  FAILED  ] CudaDsxpy.DoubleValues (4 ms)
[----------] 1 test from CudaDsxpy (4 ms total)

[----------] 1 test from CudaDtDxpy
[ RUN      ] CudaDtDxpy.ComputeFourItems
I20220922 10:22:02.735306 1813795 context_impl.cc:122] 
======================= CUDA Device Properties ======================
Cuda version         : 11.7
Device ID            : 0
Device name          : Quadro K2200
Total GPU memory     :   4042 MiB
GPU memory available :   3867 MiB
Compute capability   : 5.0
Warp size            : 32
Max threads per block: 1024
Max threads per dim  : 1024 1024 64
Max grid size        : 2147483647 65535 65535
Multiprocessor count : 5
====================================================================
I20220922 10:22:02.736486 1813795 wall_time.cc:85] 

InitCuda
                                        Delta   Cumulative
                    cublasCreate :    0.00055      0.00055
                cusolverDnCreate :    0.00046      0.00101
                  cusparseCreate :    0.00012      0.00112
       cudaStreamCreateWithFlags :    0.00001      0.00113
                       SetStream :    0.00000      0.00113
                           Total :    0.00000      0.00113

/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:183: Failure
Expected equality of these values:
  y_cpu[0]
    Which is: 4
  4.0 + 10.0 * 10.0 * 1.0
    Which is: 104
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:184: Failure
Expected equality of these values:
  y_cpu[1]
    Which is: 3
  3.0 + 20.0 * 20.0 * 2.0
    Which is: 803
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:185: Failure
Expected equality of these values:
  y_cpu[2]
    Which is: 2
  2.0 + 30.0 * 30.0 * 3.0
    Which is: 2702
/usr/local/google/home/sameeragarwal/ceres-solver/internal/ceres/cuda_kernels_test.cc:186: Failure
Expected equality of these values:
  y_cpu[3]
    Which is: 1
  1.0 + 40.0 * 40.0 * 4.0
    Which is: 6401
[  FAILED  ] CudaDtDxpy.ComputeFourItems (4 ms)
[----------] 1 test from CudaDtDxpy (4 ms total)

[----------] Global test environment tear-down
[==========] 7 tests from 6 test suites ran. (769 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] CudaDsxpy.DoubleValues
[  FAILED  ] CudaDtDxpy.ComputeFourItems

 2 FAILED TESTS
 ```

**Comment by sandwichmaker** [comment] 2022-09-22 17:28
I can replicate the non-determinism even without the flags. Its just a little bit harder. Also the set of tests that are failing also varies. So this is definitely a synchronization bug.

**Comment by joydeep-b** [comment] 2022-09-22 17:34
This smells like a stream sync issue, and I am wondering if there some missing or partial support for your GPU (I see that it has a CC = 5).
Quick hack: would you mind applying this patch and re-running?

```
diff --git a/internal/ceres/cuda_buffer.h b/internal/ceres/cuda_buffer.h
index 97d126c2..f3cb8fe9 100644
--- a/internal/ceres/cuda_buffer.h
+++ b/internal/ceres/cuda_buffer.h
@@ -122,6 +122,7 @@ class CudaBuffer {
   // data to CPU memory.
   void CopyToCpu(T* data, const size_t size) const {
     CHECK(data_ != nullptr);
+    cudaDeviceSynchronize();
     CHECK_EQ(cudaMemcpyAsync(data,
                              data_,
                              size * sizeof(T),
@@ -129,6 +130,7 @@ class CudaBuffer {
                              context_->stream_),
              cudaSuccess);
     CHECK_EQ(cudaStreamSynchronize(context_->stream_), cudaSuccess);
+    cudaDeviceSynchronize();
   }
 
   // Copy N items from another GPU memory array to the GPU memory managed by

```

**Comment by sandwichmaker** [comment] 2022-09-22 17:42
Yes that fixes it. In fact it seems only the first cudaDeviceSynchronize call is needed, not the second one. Commenting out the first one causes the test to fail but not the second one.

**Comment by joydeep-b** [comment] 2022-09-22 17:43
Ugh.
Okay, and if you don't sync the entire device, but add an additional stream sync before the memcpy?

**Comment by sandwichmaker** [comment] 2022-09-22 17:44
Yes
```
void CopyToCpu(T* data, const size_t size) const {
    CHECK(data_ != nullptr);
    cudaDeviceSynchronize();
    CHECK_EQ(cudaMemcpyAsync(data,
                             data_,
                             size * sizeof(T),
                             cudaMemcpyDeviceToHost,
                             context_->stream_),
             cudaSuccess);
    CHECK_EQ(cudaStreamSynchronize(context_->stream_), cudaSuccess);
  }
```

**Comment by joydeep-b** [comment] 2022-09-22 17:45
I mean:
```
void CopyToCpu(T* data, const size_t size) const {
    CHECK(data_ != nullptr);
    CHECK_EQ(cudaStreamSynchronize(context_->stream_), cudaSuccess);
    CHECK_EQ(cudaMemcpyAsync(data,
                             data_,
                             size * sizeof(T),
                             cudaMemcpyDeviceToHost,
                             context_->stream_),
             cudaSuccess);
    CHECK_EQ(cudaStreamSynchronize(context_->stream_), cudaSuccess);
  }
```

**Comment by joydeep-b** [comment] 2022-09-22 17:47
Oh wait, I see the bug. CL on its way.

**Comment by sandwichmaker** [comment] 2022-09-22 17:49
also why are you using cudaMemcpyAsync here at all? if you are going to wait for the synchornization anyways? why not just use cudaMemCpy

**Comment by sandwichmaker** [comment] 2022-09-22 17:49
and yes the second version also works.

**Comment by joydeep-b** [comment] 2022-09-22 17:55
"async" here means async wrt CPU. It needs to sync w.r.t the stream where all the ceres CUDA operations runs. Hence it needs to be async but launched on the correct stream, and then we sync the whole stream.

**Closed** 2022-09-22 18:46 UTC
Labels: bug
