### ISSUE TITLE
Compilation errors on jetson orin 32GB board

### ISSUE THREAD

**Issue by cchester25** [ceres-solver/ceres-solver#1065] opened 2024-05-05 06:35 UTC
The platform I am using is Jetson orin 32GB, the system is Ubuntu 20.04, and the Ceres version is 2.2.0. I have successfully compiled Ceres and am able to run the simplebundle_bundle adjuster under/build/bin. But when I use target_link_libraries (projectname ${CERES-LIBRARIES}) in my own project CMakeLists.txt, the following error occurs:
![2024-05-05 10-56-29 的屏幕截图](https://github.com/ceres-solver/ceres-solver/assets/70146927/90a514b2-2f3c-4b29-8beb-b571ef61d403)
I am confident that CUDA has been installed correctly and the path has been configured. CUDA version is 11.4.
![2024-05-05 14-31-30 的屏幕截图](https://github.com/ceres-solver/ceres-solver/assets/70146927/1fcfeb07-bcbf-4407-ac08-0cc8cd80b77f)
![2024-05-05 14-33-10 的屏幕截图](https://github.com/ceres-solver/ceres-solver/assets/70146927/12fde4ab-ad7d-4c2f-a4bb-78a301d70f67)
I hope to receive your help, thank you in advance!

**Comment by sandwichmaker** [comment] 2024-05-06 23:19
@alexsmac @sergiud any idea what maybe going on?

**Comment by sandwichmaker** [comment] 2024-09-29 20:49
Closing because of lack of follow up, and our inability to reproduce.

**Closed by sandwichmaker** 2024-09-29 20:49 UTC
