### ISSUE TITLE
Report error LNK2019 when using CostFunctionToFunctor

### ISSUE THREAD

**Issue by ivannhf** [ceres-solver/ceres-solver#982] opened 2023-07-07 14:27 UTC
I wish to use a third-party function (only take up datatype of double) in AutoDiffCostFunction. I follow the official document at http://ceres-solver.org/interfacing_with_autodiff.html#a-function-that-returns-its-value to implement in defining std::unique_ptr with CostFunctionToFunctor, the compiler will report LNK2019 and LNK1120, the main error as follows,

> [build] main_.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl ceres::DynamicCostFunctionToFunctor::DynamicCostFunctionToFunctor(class ceres::CostFunction *)" (__imp_??0DynamicCostFunctionToFunctor@ceres@@QEAA@PEAVCostFunction@1@@Z) referenced in function "public: __cdecl ceres::CostFunctionToFunctor<1,1>::CostFunctionToFunctor<1,1>(class ceres::CostFunction *)" (??0?$CostFunctionToFunctor@$00$00@ceres@@QEAA@PEAVCostFunction@1@@Z) [C:\test_ceres\src\build\test_ceres.vcxproj]
> [build] main_.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl ceres::DynamicCostFunctionToFunctor::~DynamicCostFunctionToFunctor(void)" (__imp_??1DynamicCostFunctionToFunctor@ceres@@QEAA@XZ) referenced in function "int `public: __cdecl ceres::CostFunctionToFunctor<1,1>::CostFunctionToFunctor<1,1>(class CostFunctionToFunctor<1,1>::CostFunction *)'::`1'::dtor$0" (?dtor$0@?0???0?$CostFunctionToFunctor@$00$00@ceres@@QEAA@PEAVCostFunction@1@@Z@4HA) [C:\test_ceres\src\build\test_ceres.vcxproj]
> [build] C:\test_ceres\src\build\Debug\test_ceres.exe : fatal error LNK1120: 2 unresolved externals [C:\test_ceres\src\build\test_ceres.vcxproj]

But if I didn't call the CostFunctionToFunctor, the program compiles and runs normally.

Version ceres solver installed is 2.1.0 through vcpkg (ceres:x64-windows)

Thanks.

**Comment by sandwichmaker** [comment] 2023-07-10 10:43
@ivannhf are you able to build and run all the tests ? can you share a minimal reproduction?

**Comment by ivannhf** [comment] 2023-07-10 11:47
Any single executable command for testing in windows with vcpkg? (like `make test` in Linux system)
But I can build and run all examples in the '[examples](https://github.com/ceres-solver/ceres-solver/tree/master/examples)' folder. 
I try to patch the minimum project that I compiled together with the output window log during compile.
Thanks.
[src.zip](https://github.com/ceres-solver/ceres-solver/files/12001476/src.zip)
[output.log](https://github.com/ceres-solver/ceres-solver/files/12001488/output.log)

**Comment by sandwichmaker** [comment] 2023-07-10 15:02
@ivannhf I tried your code on my macos laptop (only difference is that I did not use your cmakefile) and it compiles just fine. So I am wondering if we are missing something that is specific to windows/vc++. I do not use windows so I am not completely sure.

Is the problem here that the compiler cannot find the destructor?

**Comment by ivannhf** [comment] 2023-07-10 15:15
Seems it appears three errors related to ceres::DynamicCostFunctionToFunctor, which can't resolve external symbol on `ceres::DynamicCostFunctionToFunctor::DynamicCostFunctionToFunctor(class ceres::CostFunction *)`, `ceres::DynamicCostFunctionToFunctor::operator()(double const * const *,double *)const`, and `ceres::DynamicCostFunctionToFunctor::~DynamicCostFunctionToFunctor(void)`. 
But the problem is the code didn't inlcude the DynamicCostFunctionToFunctor, only the CostFunctionToFunctor.

**Comment by ivannhf** [comment] 2023-07-11 12:34
I also tried to deploy the code in Ubuntu 18.04, and the code compiled normally. Seems it's msvc problem.

**Comment by sandwichmaker** [comment] 2023-08-08 01:39
@sergiud do yo know what maybe going on here and the workaround for this with msvc?

**Comment by sergiud** [comment] 2023-08-08 10:23
The issue is likely is in @ivannhf setup since a MinGW based vcpkg installation is used in his MSVC project. This mix probably causes the linker errors.

Other than that, I suggest submitting the issue to vcpkg folks how can exactly tell what is wrong here.

**Comment by sergiud** [comment] 2023-09-09 18:25
Let me close the issue since the problem is vcpkg specific.

**Closed by sergiud** 2023-09-09 18:25 UTC
