### ISSUE TITLE
SuiteSparse 6.0.0 is not found

### ISSUE THREAD

**Issue by thierry-FreeBSD** [ceres-solver/ceres-solver#919] opened 2022-11-13 17:00 UTC
Trying to build ceres-solver 2.1.0 against SuiteSparse 6.0.0 disables the support of suitesparse:

```
-- Disabling use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
-- Did not find CUDA library, disabling CUDA support.
-- Found LAPACK library: /usr/local/lib/libopenblas.so;/usr/local/lib/libopenblas.so
-- Found CHOLMOD headers in: /usr/local/include/suitesparse
-- Found CHOLMOD library: /usr/local/lib/libcholmod.so
-- Found SPQR headers in: /usr/local/include/suitesparse
-- Found SPQR library: /usr/local/lib/libspqr.so
-- Found Config headers in: /usr/local/include/suitesparse
-- Found Config library: /usr/local/lib/libsuitesparseconfig.so
-- Found AMD headers in: /usr/local/include/suitesparse
-- Found AMD library: /usr/local/lib/libamd.so
-- Found CAMD headers in: /usr/local/include/suitesparse
-- Found CAMD library: /usr/local/lib/libcamd.so
-- Found CCOLAMD headers in: /usr/local/include/suitesparse
-- Found CCOLAMD library: /usr/local/lib/libccolamd.so
-- Found COLAMD headers in: /usr/local/include/suitesparse
-- Found COLAMD library: /usr/local/lib/libcolamd.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS: /usr/local/include (found version "5.1.0") 
-- Failed to find some/all required components of SuiteSparse.: Found unsuitable version "..", but required is at least "4.0" (found /usr/local/include/suitesparse, found components: CHOLMOD SPQR Config AMD CAMD CCOLAMD COLAMD)
-- Did not find all SuiteSparse dependencies, disabling SuiteSparse support.
-- Found CXSparse: /usr/local/include/suitesparse (found version "4.0.0") 
-- Found CXSparse version: 4.0.0, building with CXSparse.

```

**Comment by sandwichmaker** [comment] 2022-11-13 17:18
Suitesparse 6.0.0 was released with a new build system a few days ago. I suspect it has to do with that. @alexsmac and @sergiud can you guys take a look please?

**Comment by sergiud** [comment] 2022-11-13 17:19
The problem is only with version identification: SuiteSparse 6.0 delimits the version component name from its value by [multiple spaces now](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/d42beebdcc6b98c7fb2f7f2927f32c19e0f602d0/SuiteSparse_config/SuiteSparse_config.h#L488-L491).

Can you try replacing the space after each macro name by `[ \t]+` here?
https://github.com/ceres-solver/ceres-solver/blob/5d53d1ee3839d74cbc759785eceef9e225107dfb/cmake/FindSuiteSparse.cmake#L407-L420
Specifically `#define SUITESPARSE_MAIN_VERSION[ \t]+[0-9]+` and so on.

**Comment by thierry-FreeBSD** [comment] 2022-11-14 19:22
Indeed, with the attached patch, SuiteSparse 6.0.1
[patch-cmake_FindSuiteSparse.cmake.txt](https://github.com/ceres-solver/ceres-solver/files/10006372/patch-cmake_FindSuiteSparse.cmake.txt)
 is well detected, and ceres-solver builds without error and with SuiteSparse enabled.

But note that with the latest versions, SuiteSparse installs its own cmake modules, and this file FindSuiteSparse.cmake is no more needed:

```
$ ls /usr/local/lib/cmake/SuiteSparse/*
/usr/local/lib/cmake/SuiteSparse/FindAMD.cmake                  /usr/local/lib/cmake/SuiteSparse/FindCHOLMOD.cmake              /usr/local/lib/cmake/SuiteSparse/FindKLU.cmake                  /usr/local/lib/cmake/SuiteSparse/FindSPQR_CUDA.cmake
/usr/local/lib/cmake/SuiteSparse/FindBTF.cmake                  /usr/local/lib/cmake/SuiteSparse/FindCOLAMD.cmake               /usr/local/lib/cmake/SuiteSparse/FindLDL.cmake                  /usr/local/lib/cmake/SuiteSparse/FindSPQR.cmake
/usr/local/lib/cmake/SuiteSparse/FindCAMD.cmake                 /usr/local/lib/cmake/SuiteSparse/FindCXSparse.cmake             /usr/local/lib/cmake/SuiteSparse/FindMongoose.cmake             /usr/local/lib/cmake/SuiteSparse/FindSuiteSparse_config.cmake
/usr/local/lib/cmake/SuiteSparse/FindCCOLAMD.cmake              /usr/local/lib/cmake/SuiteSparse/FindGraphBLAS.cmake            /usr/local/lib/cmake/SuiteSparse/FindRBio.cmake                 /usr/local/lib/cmake/SuiteSparse/FindUMFPACK.cmake
/usr/local/lib/cmake/SuiteSparse/FindCHOLMOD_CUDA.cmake         /usr/local/lib/cmake/SuiteSparse/FindKLU_CHOLMOD.cmake          /usr/local/lib/cmake/SuiteSparse/FindSPEX.cmake

```

**Comment by sergiud** [comment] 2022-11-14 19:39
Thanks for the feedback. `FindSuiteSparse.cmake` however is still very much needed for supporting older versions of SuiteSparse. Aside from that, I don't see any advantages of using those find modules over our implementation.

**Comment by thierry-FreeBSD** [comment] 2022-11-16 21:48
Follow-up: fixing ceres-solver is not sufficient, CeresConfig.cmake must also be fixed!

Trying to build openturns-1.19 fails with the following error:

```
-- Found CXSparse: /usr/local/include/suitesparse (found suitable version "4.0.0", minimum required is "4.0.0") 
CMake Error at /usr/local/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  find_package called with invalid argument "6."
Call Stack (most recent call first):
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:183 (find_dependency)
  CMakeLists.txt:362 (find_package)


-- Found required Ceres dependency: Eigen version 3.4.0 in /usr/local/share/eigen3/cmake
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.1.0 installed in: /usr/local with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations, OpenMP, Multithreading]

```

**Comment by sergiud** [comment] 2022-11-16 21:52
Unfortunately, your patch is incorrect. Please see my [CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/23460) which out for review.

**Comment by thierry-FreeBSD** [comment] 2022-11-17 17:41
Thanks, this patch is OK!

**Closed** 2022-11-18 17:48 UTC
Labels: cmake
