### ISSUE TITLE
Missing Scale factor in QuaternionParameterization?

### ISSUE THREAD

**Issue by cfneuhaus** [ceres-solver/ceres-solver#311] opened 2017-09-12 13:23 UTC
In the current implementation of `QuaternionParameterization`, the local parametrization for rotations is equal to (angle/2) * axis. This is because the `QuaternionParameterization::Plus` function is implemented as 

```
bool QuaternionParameterization::Plus(const double* x,
                                      const double* delta,
                                      double* x_plus_delta) const {
  const double norm_delta =
      sqrt(delta[0] * delta[0] + delta[1] * delta[1] + delta[2] * delta[2]);
  if (norm_delta > 0.0) {
    const double sin_delta_by_delta = (sin(norm_delta) / norm_delta);
    double q_delta[4];
    q_delta[0] = cos(norm_delta);
    q_delta[1] = sin_delta_by_delta * delta[0];
    q_delta[2] = sin_delta_by_delta * delta[1];
    q_delta[3] = sin_delta_by_delta * delta[2];
    QuaternionProduct(q_delta, x, x_plus_delta);
  } else {
    for (int i = 0; i < 4; ++i) {
      x_plus_delta[i] = x[i];
    }
  }
  return true;
}
```

I recently stumbled across this. Isn't it a bit unusual not to use the angle*axis representation for the local parametrization. Wouldn't it make sense to multiply the angle by *0.5 inside of the `Plus` function implementation, so that the function is directly "compatible" to the `AngleAxisToQuaternion` / `QuaternionToAngleAxis` functions?

Background: I recently wanted to put an absolute prior on a Quaternion. For this, I used a function that essentially does the inverse of the `Plus` function: It takes two quaternions and computes the angle*axis difference between them. I then defined a cost function with

`residual = InvL * Minus(q, quat_mu)`

where q is the quaternion variable block, `quat_mu` is the mean of the quaternion prior and `InvL` is the inverse covariance square root that is typically used to achieve normally distributed residuals. Optimization works as expected, however when computing the posterior covariance matrix of q in the tangent space, it is not equal to the covariance of my prior. Changing my `Minus` function to yield (angle/2)*axis notation fixes the problem. But adding the /2 there feels a bit arbitrary, and it seems like it should be really inside of the `Plus` function.

**Comment by sandwichmaker** [comment] 2017-09-26 12:25
please see discussion on the mailinglist.  The implementation is correct. The scale factor if introduced will just get undone/rescaled in the jacobian of the local parameterization. 

The tangent space issue is interesting, I will think about it some more.

**Comment by vrfneuhaus** [comment] 2017-09-26 13:54
Note: I am not claiming the implementation is 'wrong' -- after all it's just a scale factor on the residual, so optimization is going to work fine. I am just saying that the choice for this (in my opinion) "unnecessary/unusual" scale factor in the tangent space can force users to compensate for it for covariance computations, as I had to when implementing my `Minus` function.

A possible alternative would be to provide a matching `Minus` function, for (all?) local parametrizations, so that users can implement priors on their local parametrizations. But of course, now they would have to be careful to watch the units within their covariance matrices, which are going to have (angle/2)^2 units on their diagonals for the QuaternionParametrization, which again shows how unusual that scale factor is...

**Comment by cfneuhaus** [comment] 2017-09-26 13:57
(Sorry, I had to repost because I was using the wrong Github account ;) )

Note: I am not claiming the implementation is 'wrong' -- after all it's just a scale factor on the residual, so optimization is going to work fine. I am just saying that the choice for this (in my opinion) "unnecessary/unusual" scale factor in the tangent space can force users to compensate for it for covariance computations, as I had to when implementing my Minus function.

A possible alternative would be to provide a matching Minus function, for (all?) local parametrizations, so that users can implement priors on their local parametrizations. But of course, now they would have to be careful to watch the units within their covariance matrices, which are going to have (angle/2)^2 units on their diagonals for the QuaternionParametrization, which again shows how unusual that scale factor is...

**Comment by keir** [comment] 2017-12-27 14:39
@sandwichmaker Any update here?

**Comment by NikolausDemmel** [comment] 2018-01-26 13:29
Just a few comments. Both variants make sense. I cannot really say which is preferrable.

Maybe whatever the choice, stating this distinction clearly in a code comment would be beneficial.

 - Sola discusses this distinction in his [tech report](http://www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf). In some sense, the current implementation is more natural, since the lie algebra for the lie group of unit quaternions is one of half-velocities. On the other hand, choosing a scaled tangent space makes it more directly related to the tangent space of rotation matrices, which is maybe more intuitive when interpreting things like covariances as you describe. So I'm not sure which is better...
 - Sophus implements a [local parameterization for SE(3)](https://github.com/strasdat/Sophus/blob/master/test/ceres/local_parameterization_se3.hpp) with the full SE(3) exponential map as a retraction. It internally uses quaternions, which is meant to be an implementation detail. Therefore the tangent space is chosen such that it corresponds to the (parameterization of) the SE(3) tangent space, i.e. velocities instead of hald-velocities. Therefore, this is also taken into account in the [Jacobian](https://github.com/strasdat/Sophus/blob/7ef9cff9e9f7b258ab3a2e442b08ea59897ecdec/sophus/so3.hpp#L162-L186).
 - The choice of a constant factor like for the tangent space is in general not completely irrelevant. Constant factors will influence how the problem is conditioned and therefore the numerical solution. Albeit with a factor of 2 that should not rally have noticable implications in this case, I would assume.

**Comment by sandwichmaker** [comment] 2020-05-22 22:38
Given that there is likely a ton of code which depends on this implementation at this point, I suspect that changing this is not a great idea. Especially in light of the discussion on this thread where there are reasonable arguments for both choices.  So I am going to go ahead and close this.  Please feel free to re-open if you feel strongly about this, I am happy to converse more.

**Closed by sandwichmaker** 2020-05-22 22:38 UTC
